### ISSUE TITLE
Italics inside tribble(); vitae r package

### ISSUE THREAD

**Issue by BiotechPedro** [mitchelloharawild/vitae#109]
Hi! First of all, thank you for this package. It's rocks!

I'd tried lots of r commands like expression(italics()) or markdown_latex() and also latex syntax \emph{}, \textit{}, but none generates italics text. 

Do you know if it is possible?

```r
tribble(
  ~ degree, ~ uni, ~ loc, ~ dates, ~ details,
  "BSc", "University", "Country", "2015 - 2019", markdown_latex("Thesis: *E. coli* O157:H7"),
  "MSc", "University", "Country", "2019 - present",""
) %>% 
  detailed_entries(uni, loc, degree, dates, details)
```

**Comment by mitchelloharawild** [comment]
You can use latex syntax if you set `.protect = FALSE` in `detailed_entries()`.

**Comment by BiotechPedro** [comment]
Yes! It works. Thank you !!
