### ISSUE TITLE
Hyndman CV - bibsetup issue, file not compiling

### ISSUE THREAD

**Issue by abhijitsharma111** [mitchelloharawild/vitae#113]
After updating to Texlive 2020 the Hyndman CV rmd file has stopped compiling for some reason. Rstudio had a version error and asked me to update to Texlive 2020. I have updated all R packages as well as biblatex but still cannot compile. The error message I get with the example file (https://github.com/robjhyndman/CV) and my file are identical and given below:

! Undefined control sequence.
\biburlsetup ->\Urlmuskip 
                          \biburlbigskip \mathchardef \UrlBigBreakPenalty =\...
l.451 ...ory=bib-rjhpubs.bib-1670812,heading=none]
                                                  \setcounter{papers}{0} 

Error: LaTeX failed to compile. See https://yihui.org/tinytex/r/#debugging for debugging tips. See log for more info.
Execution halted

https://github.com/robjhyndman/CV

```r
I simply cloned the Hyndman  CV folder and ran knit for RobHyndmanCV.Rmd. This gave the error message above
```
Thanks for your help.

**Comment by mitchelloharawild** [comment]
I updated to tl2020 today and was able to build this CV without issue.
Could you post your `sessionInfo()`?

Perhaps this may help: https://tex.stackexchange.com/questions/167057/undefined-control-sequence-biburlsetup-urlmuskip-error-when-compiling-wit

**Comment by abhijitsharma111** [comment]
Hi thanks for your message, the issue is not related to an orphan url.sty file which I have checked. 

────────────────────────────────────────────
 setting  value                       
 version  R version 3.6.3 (2020-02-29)
 os       macOS Mojave 10.14.6        
 system   x86_64, darwin15.6.0        
 ui       RStudio                     
 language (EN)                        
 collate  en_GB.UTF-8                 
 ctype    en_GB.UTF-8                 
 tz       Europe/London               
 date     2020-04-17                  

─ Packages ──────────────────────────────────────────────────────────────────────────────
 package     * version date       lib source        
 assertthat    0.2.1   2019-03-21 [1] CRAN (R 3.6.0)
 cli           2.0.2   2020-02-28 [1] CRAN (R 3.6.0)
 crayon        1.3.4   2017-09-16 [1] CRAN (R 3.6.0)
 digest        0.6.25  2020-02-23 [1] CRAN (R 3.6.0)
 dplyr         0.8.5   2020-03-07 [1] CRAN (R 3.6.0)
 evaluate      0.14    2019-05-28 [1] CRAN (R 3.6.0)
 fansi         0.4.1   2020-01-08 [1] CRAN (R 3.6.0)
 glue          1.3.2   2020-03-12 [1] CRAN (R 3.6.0)
 htmltools     0.4.0   2019-10-04 [1] CRAN (R 3.6.0)
 knitr         1.28    2020-02-06 [1] CRAN (R 3.6.0)
 magrittr      1.5     2014-11-22 [1] CRAN (R 3.6.0)
 pillar        1.4.3   2019-12-20 [1] CRAN (R 3.6.0)
 pkgconfig     2.0.3   2019-09-22 [1] CRAN (R 3.6.0)
 purrr         0.3.3   2019-10-18 [1] CRAN (R 3.6.0)
 R6            2.4.1   2019-11-12 [1] CRAN (R 3.6.0)
 Rcpp          1.0.4   2020-03-17 [1] CRAN (R 3.6.0)
 rlang         0.4.5   2020-03-01 [1] CRAN (R 3.6.0)
 rmarkdown     2.1     2020-01-20 [1] CRAN (R 3.6.0)
 rstudioapi    0.11    2020-02-07 [1] CRAN (R 3.6.0)
 sessioninfo   1.1.1   2018-11-05 [1] CRAN (R 3.6.0)
 tibble        2.1.3   2019-06-06 [1] CRAN (R 3.6.0)
 tidyselect    1.0.0   2020-01-27 [1] CRAN (R 3.6.0)
 vitae         0.2.0   2019-07-12 [1] CRAN (R 3.6.0)
 withr         2.1.2   2018-03-15 [1] CRAN (R 3.6.0)
 xfun          0.12    2020-01-13 [1] CRAN (R 3.6.0)
 yaml          2.2.1   2020-02-01 [1] CRAN (R 3.6.0)

[1] /Library/Frameworks/R.framework/Versions/3.6/Resources/library

**Comment by mitchelloharawild** [comment]
Could you test out the development version of vitae? I have made some changes today which may resolve the issue.

**Comment by abhijitsharma111** [comment]
Thanks - I have installed the dev version of vitae and rerun - unfortunately I still get an error:

output file: RobHyndmanCV.knit.md

! LaTeX Error: Command \bibfont undefined.

Error: LaTeX failed to compile RobHyndmanCV.tex. See https://yihui.org/tinytex/r/#debugging for debugging tips. See RobHyndmanCV.log for more info.

**Comment by mitchelloharawild** [comment]
Great, that is working properly then. There is an issue with Rob's template as it uses the older latex only implementation of `bibliography_entries()`. Yesterday I added support for CSL files and I am in the process of making a CSL file that matches the bibliography formatting originally used by this package.

To get Rob's template to compile (albeit with fairly bad looking bibliography until the CSL is added), simply remove this line:
https://github.com/robjhyndman/CV/blob/c01ab7f847369b200f84a2cf20ae624a8eddf2be/RobHyndmanCV.Rmd#L262

**Comment by abhijitsharma111** [comment]
Thanks very much for your help, I can confirm that the file is now compiling even though (as you mentioned) the references are not formatting correctly. best wishes

**Comment by mitchelloharawild** [comment]
Great. Active discussion on the references for this CV can be found here: https://github.com/robjhyndman/CV/issues/5
