### ISSUE TITLE
Inclusion of month field in .bib causing problems

### ISSUE THREAD

**Issue by acircleda** [mitchelloharawild/vitae#123]
I am using the following to generate my .bib files:

```
gsheet::gsheet2tbl("https://docs.google.com/spreadsheets/d/1qbMpXHXm41q69prUVjpQFfP_mMXjORNxFP_IbAoCuKo/edit#gid=318960497") %>%
  filter(category=="regional") %>%
  mutate(month = as.numeric(month)) %>%
  select(-category, -month) %>%
  RefManageR::as.BibEntry() %>% 
  RefManageR::WriteBib("bib/conf_regional.bib", biblatex=T)
```

Example:

```
@Conference{2,
  author = {Anthony Schmidt},
  title = {Academic reading circles},
  year = {2016},
  organization = {Southeast TESOL Regional Conference, Louisville, Kentucky},
  note = {Conference session},
  booktitle = {conference},
  key = {2},
}
```

When I create this **without** the month field, everything is ordered correctly by year.
When I create this **with** the month field, the order is semi-random *and* the month does not display (see below). For conferences, the month should display per APA 6 and 7.

![image](https://user-images.githubusercontent.com/51770624/82823085-e8f53380-9e74-11ea-8bc5-6bc21765f743.png)

I'm not sure if this is user error, an issue with the CSL file, an issue with the .bib file, or an issue with biblatex,

**Comment by mitchelloharawild** [comment]
Unless you've used a custom CSL file, the order should match the order of the data (allowing you to use `arrange()` or any other row ordering function to customise the display order).
You are of course welcome to use any CSL that you like which includes sorting instructions within the style.

**Comment by acircleda** [comment]
I am using the Zotero APA 7 for Cvs. I did open an issue with the CSL author, thinking it was an issue with the formatting. Seems a little bit more complicated

**Comment by bwiernik** [comment]
Yes, for CSL styles, you should be storing data in a CSL format, either CSL-JSON or CSL YAML. If you use BibTeX with pandoc, it internally converts data in any other format to CSL-JSON, which won't work particuarly well for non-journal/non-book items, as seen here.

**Comment by mitchelloharawild** [comment]
Support for non-bib files will be added in https://github.com/mitchelloharawild/vitae/issues/112.
Thanks for your insight @bwiernik.

**Comment by bwiernik** [comment]
I have a cslr package in the works for processing citeproc json. Should be done some time this summer. Not sure on exactly your needs, but let me know if it might be helpful.

**Comment by mitchelloharawild** [comment]
In a local branch I'm using `rmarkdown::pandoc_citeproc_convert` to parse bib into yaml (if yaml is provided, then this step is not used), and then `yaml::yaml.load()` to read the citations as data for user arrangement / manipulation. Can you foresee any issues with this approach?

**Comment by bwiernik** [comment]
Converting bib is only going to approximately work. That function should work as well as using bib direct with pandoc/Rmarkdown. The best approach would be to read in CSL JSON using jsonlite. 

You could just read in .json files as-is. cslr will have more robust validation and checking to be sure the data are valid CSL data.

**Comment by mitchelloharawild** [comment]
Yes, but if the user provides bib then that is all that can be done. The new approach would allow users to provide json or yaml if they desire. Are json and yaml equivalent in capability here?

**Comment by bwiernik** [comment]
Yes, they are the same fields, just presented in different formats. YAML is suitable for including directly inside a markdown doc, whereas JSON is better if stored externally.

**Comment by brooksambrose** [comment]
> Unless you've used a custom CSL file, the order should match the order of the data (allowing you to use `arrange()` or any other row ordering function to customise the display order).

@mitchelloharawild FWIW, the `apa-cv.csl` file that serves as the default does indeed overwrite any sorting done on the data by `arrange()`. There are many sorting sections in the csl, and they all look like this:

https://github.com/mitchelloharawild/vitae/blob/128246082b4ecdf2b1820f599e3f3d9d214d9ac2/inst/apa-cv.csl#L1400

```
    <sort>
      <key macro="date-sort-group" sort="descending"/>
      <key macro="date-sort-date" sort="descending"/>
      <key variable="status"/>
      <key macro="author-bib"/>
      <key macro="title"/>
    </sort>
```

Not sure why the sort macros in the default csl don't work, but removing these sections from the csl creates the desired behavior of the order being the same as the data.

**Comment by mitchelloharawild** [comment]
Thanks, I thought I had removed these (evidently not).
Could you verify that 34cea325b8016ee80ba440b0f9002a1b7a02d28a fixes this issue?

**Comment by bwiernik** [comment]
apa-cv.csl does sort the bibliography reverse chronologically. If you want to manually sort the cv in vitae, generate _citations_ with apa-cv.csl. These have the same formatting as the bibliography, but will be in whatever order you specify.

**Comment by brooksambrose** [comment]
@mitchelloharawild Yup that does, it thanks!

**Comment by mitchelloharawild** [comment]
Closing as the package now supports and uses CSL formatting of bibliographies.
The default is to match the order of the `bibliography_entries()` tibble, which can be customised with `arrange()`.
