### ISSUE TITLE
remove the horizontal lines after section titles in awesome-cv

### ISSUE THREAD

**Issue by duleise** [mitchelloharawild/vitae#124]
Could not find similar issues here. I will post it anyway.
I like the style of awesome-cv except the lines.
I can not figure out from .cls file which lines are controlling this.
Any suggestions?
Thanks.

**Comment by mitchelloharawild** [comment]
The horizontal line is added here:
https://github.com/mitchelloharawild/vitae/blob/5b33de8744911467a51a6c40d4c649a69b126b49/inst/rmarkdown/templates/awesomecv/skeleton/awesome-cv.cls#L580
