### ISSUE TITLE
Latin characters not rendering as they should

### ISSUE THREAD

**Issue by egoipse** [mitchelloharawild/vitae#125]
Hi,

I loved the idea of this package. And also liked the examples of CVs I saw. I think RMarkdown is the way to go from now on for reproductible CVs.

However, the latin special characters are not rendering correctly once the button "Knit" is clicked. For example, my surname is Giménez, but is rendered as GimÃľnez, as you can see in the attached image from my CV rendered with `vitae`.

![Captura realizada el 2020-06-21 20 16 13](https://user-images.githubusercontent.com/2198733/85238668-83598000-b3fd-11ea-998f-ade3cf30252f.png)

I also tried forcing the utf-8 encoding with `rmarkdown::render("cv.rmd", encoding="UTF-8")`. The output is the same, however.

My guess is that it has something to do with pandoc or other vitae package dependencies. However, I didn't find any documentation that solves the issue.

I'm pretty sure that this package would get universal if this kind of issues are solved.

Any help on this will be appreciated.

Here's my session info:

```
R version 3.6.3 (2020-02-29)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: elementary OS 5.1.5 Hera

Matrix products: default
BLAS:   /usr/lib/x86_64-linux-gnu/blas/libblas.so.3.7.1
LAPACK: /usr/lib/x86_64-linux-gnu/lapack/liblapack.so.3.7.1

locale:
 [1] LC_CTYPE=C.UTF-8       LC_NUMERIC=C          
 [3] LC_TIME=C.UTF-8        LC_COLLATE=C.UTF-8    
 [5] LC_MONETARY=C.UTF-8    LC_MESSAGES=C.UTF-8   
 [7] LC_PAPER=C.UTF-8       LC_NAME=C             
 [9] LC_ADDRESS=C           LC_TELEPHONE=C        
[11] LC_MEASUREMENT=C.UTF-8 LC_IDENTIFICATION=C   

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods  
[7] base     

other attached packages:
[1] glue_1.4.1        readxl_1.3.1      RefManageR_1.2.12
[4] vitae_0.2.2      

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.4.6     rstudioapi_0.11  xml2_1.3.2      
 [4] knitr_1.28       magrittr_1.5     tidyselect_1.1.0
 [7] R6_2.4.1         rlang_0.4.6      bibtex_0.4.2.2  
[10] plyr_1.8.6       stringr_1.4.0    httr_1.4.1      
[13] dplyr_1.0.0      tools_3.6.3      packrat_0.5.0   
[16] xfun_0.15        ellipsis_0.3.1   tibble_3.0.1    
[19] lifecycle_0.2.0  crayon_1.3.4     purrr_0.3.4     
[22] vctrs_0.3.1      stringi_1.4.6    cellranger_1.1.0
[25] compiler_3.6.3   pillar_1.4.4     generics_0.0.2  
[28] jsonlite_1.6.1   lubridate_1.7.9  pkgconfig_2.0.3 
```

**Comment by mitchelloharawild** [comment]
Could you provide an MRE for this? Please adapt and share your `cv.rmd` file to contain the bare minimum to get this issue.

**Comment by egoipse** [comment]
Sure. MRE stands for...?

**Comment by mitchelloharawild** [comment]
Minimally reproducible example. Some guidelines on this can be found here: https://www.tidyverse.org/help/

**Comment by egoipse** [comment]
Thanks. Here it goes, with front matter YAML included:

```
```
---
name: Daniel M.
surname: Giménez
phone: +56 9 7580 1985
www: danielgimenez.me
email: "daniel.gimenez@me.com"
docname: CV-DG
output: 
  vitae::moderncv:
    theme: banking
---
```

```{r inicio, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)

library(vitae)
library(RefManageR)
library(readxl)
library(glue)
```

Daniel M. Giménez

These spanish words are not rendering as they should:

- Mañana
- Comió
- Ápero
- Cárcamo
- Influí
- Tampoco ésta
- No es la única
- Ungüento

The same happens with capitalized vocals: Á, É, Í, Ó, Ú, Ü... 

```

**Comment by egoipse** [comment]
By the way, I also tried changing the locales. The same output...

**Comment by julianlavila** [comment]
I have the same issue, can´t use latin characters

**Comment by julianlavila** [comment]
> Hi,
> 
> I loved the idea of this package. And also liked the examples of CVs I saw. I think RMarkdown is the way to go from now on for reproductible CVs.
> 
> However, the latin special characters are not rendering correctly once the button "Knit" is clicked. For example, my surname is Giménez, but is rendered as GimÃľnez, as you can see in the attached image from my CV rendered with `vitae`.
> 

I found a solution, in the first r chunk just include the encoding instruction in the source command.

source(file = here("r","data.r"),encoding="UTF-8")

**Comment by mitchelloharawild** [comment]
To change the font you'll need to look into the cls file. Alternatively you may find some help by searching for how to change the font for a given template. For example, using moderncv - https://tex.stackexchange.com/questions/31534/change-font-used-by-moderncv

**Comment by egoipse** [comment]
Hi @julianlavila , thanks for your answer and your solution.

I'm not quite sure to understand it completly. When you source like this in the first chunk...  

> source(file = here("r","data.r"),encoding="UTF-8")

what exactly are you sourcing?

RMarkdown files admits `sys.source` inside code chunks. Plain `source` should output an eval error.

And your file extension (`.r`) looks like a script file, but the file name seems that you are sourcing the data for the CV.

It will be great to get more details on the solution.

Thanks in advance!

**Comment by brianamaya01** [comment]
Hi @egoipse , I have the same problem with vitae::awesome.cv. Nevertheless, I find the answer in [this conversation](https://stackoverflow.com/questions/5031630/how-to-source-r-file-saved-using-utf-8-encoding) with that function: 

```{r}
source1<- function(f, encoding = "UTF-8"){
  l <- readLines(f, encoding=encoding)
    eval(parse(text=l),envir=.GlobalEnv)
}

source1(here("r","data.r"))

```

**Comment by mitchelloharawild** [comment]
Closing as this appears to be resolved. Appropriately setting the encoding of the file appears to fix this issue.
