### ISSUE TITLE
Support Chinese

### ISSUE THREAD

**Issue by k-farruh** [mitchelloharawild/vitae#128]
If put Chinese character, vitae render it as an unknown character.
Rmarkdown can render a chinese characters.

The code below:

```

---
name: Marie
surname: Curie
position: "数据科学技能"
address: "数据科学技能"
phone: +1 22 3333 4444
www: mariecurie.com
email: "Marie.Curie@ens.fr"
twitter: mariecurie
github: mariecurie
linkedin: mariecurie
date: "`r format(Sys.time(), '%B %Y')`"
output: vitae::awesomecv
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
library(vitae)
`` 

# 数据科学技能

 * 数据科学技能
 * 数据科学技能
 * 数据科学技能

```

**Comment by mitchelloharawild** [comment]
@DanyangDai might be able to help with this one.

**Comment by DanyangDai** [comment]
Hello 

I created my Chinese CV using vitae::awesomecv 

You need to add a LaTeX package xeCJK under the yaml using `header-includes:` to support the Chinese characteristics. 
For any other LaTeX packages you want to use, you can list them all under `header-includes:` 

``` 
 ---
name: Marie
surname: Curie
position: "数据科学技能"
address: "数据科学技能"
phone: +1 22 3333 4444
www: mariecurie.com
email: "Marie.Curie@ens.fr"
twitter: mariecurie
github: mariecurie
linkedin: mariecurie
date: "`r format(Sys.time(), '%B %Y')`"
output: vitae::awesomecv
header-includes:
- \usepackage{xeCJK}
---
```

**Comment by k-farruh** [comment]
> Hello
> 
> I created my Chinese CV using vitae::awesomecv
> 
> You need to add a LaTeX package xeCJK in the yaml under `header-includes:` to support the Chinese characteristics.
> For any other LaTeX packages you want to use, you can list them all under `header-includes:`
> 
> ```
>  ---
> name: Marie
> surname: Curie
> position: "数据科学技能"
> address: "数据科学技能"
> phone: +1 22 3333 4444
> www: mariecurie.com
> email: "Marie.Curie@ens.fr"
> twitter: mariecurie
> github: mariecurie
> linkedin: mariecurie
> date: "`r format(Sys.time(), '%B %Y')`"
> output: vitae::awesomecv
> header-includes:
> - \usepackage{xeCJK}
> ---
> ```

Hello
Thank you very much, it helped.

Another question:
If created a section with two characters it gives an error 
```
! Argument of \@sectioncolor has an extra }.
<inserted text> 
                \par 
l.122 \section{学术}\label{ux5b66ux672f}}

Error: LaTeX failed to compile Untitled.tex. See https://yihui.org/tinytex/r/#debugging for debugging tips. See Untitled.log for more info.
Execution halted
```
If changed to three or more characters it works well.
How can I create a section with two characters?

**Comment by DanyangDai** [comment]
I am not too sure about that as I don't have sections that only contains two characters. But I think it is something to do with the highlight feature for each section. In the vitae::awesomecv templet, it highlight the first three character in each section. If you have characters that is less than three, it will not work. 

Try this at the beginning of your text part of R Markdown file: 
```
\renewcommand*{\sectionstyle}[1]{{\fontsize{16pt}{1em}\bodyfont\bfseries\color{text}#1}}
```
This allow you to have section which has less than three characters but no highlight for your section.

**Comment by k-farruh** [comment]
> I am not too sure about that as I don't have sections that only contains two characters. But I think it is something to do with the highlight feature for each section. In the vitae::awesomecv templet, it highlight the first three character in each section. If you have characters that is less than three, it will not work.
> 
> Try this at the beginning of your text part of R Markdown file:
> 
> ```
> \renewcommand*{\sectionstyle}[1]{{\fontsize{16pt}{1em}\bodyfont\bfseries\color{text}#1}}
> ```
> 
> This allow you to have section which has less than three characters but no highlight for your section.

Thank you, exacly. Just checked it works without hightlight.

**Comment by mitchelloharawild** [comment]
Thanks @DanyangDai.
