### ISSUE TITLE
ORCiD in header

### ISSUE THREAD

**Issue by hollzzar** [mitchelloharawild/vitae#129]
Thank you for your work, this is a great package. I was wondering if it would be possible to add an option to include an ORCiD in the header, similarly to how my website and GitHub appear with the relevant icons and web links.

**Comment by RLumSK** [comment]
At least for the template`awesome-cv` this is already implemented (#64).

**Comment by norcalbiostat** [comment]
Can this be added to the hyndman template as well?

**Comment by robjhyndman** [comment]
ORCID is already part of the Hyndman template. Just add your ORCID number in the yaml header like this.

```
orcid: "0000-0002-2140-5352"
```

**Comment by mitchelloharawild** [comment]
Closing as ORCiD support is dependent on template choice, until #69 is added to generalise social icon support.
