### ISSUE TITLE
Issue compiling default markdown file on Windows computer

### ISSUE THREAD

**Issue by marcyshieh** [mitchelloharawild/vitae#133]
I've been having some issues compiling the default .Rmd file on a Windows computer. I am able to do it on a Mac, however.

On a Windows computer, I keep getting the following error:

```
Error: LaTeX failed to compile CV2.tex. See https://yihui.org/tinytex/r/#debugging for debugging tips.
In addition: Warning messages:
1: In RefManageR::as.BibEntry(.) :
  rownames of data.frame not meaningful for creating keys
2: In system2(..., stdout = if (use_file_stdout()) f1 else FALSE, stderr = f2) :
  'CreateProcess' failed to run 'C:\Users\mshieh2\AppData\Roaming\TinyTeX\bin\win32\pdflatex.exe -halt-on-error -interaction=batchmode "CV2.tex"'
Execution halted
```

**Comment by mitchelloharawild** [comment]
Please provide your session information for the compilation with `sessioninfo::session_info()`.

**Comment by marcyshieh** [comment]
> Please provide your session information for the compilation with `sessioninfo::session_info()`.

I updated the above error and my session info is below:

`> sessioninfo::session_info()
- Session info ----------------------------------------------------
 setting  value                       
 version  R version 4.0.2 (2020-06-22)
 os       Windows Server x64          
 system   x86_64, mingw32             
 ui       RStudio                     
 language (EN)                        
 collate  English_United States.1252  
 ctype    English_United States.1252  
 tz       America/Chicago             
 date     2020-09-27                  

- Packages --------------------------------------------------------
 package     * version date       lib source        
 assertthat    0.2.1   2019-03-21 [2] CRAN (R 4.0.2)
 bibtex        0.4.2.3 2020-09-19 [1] CRAN (R 4.0.2)
 cli           2.0.2   2020-02-28 [2] CRAN (R 4.0.2)
 crayon        1.3.4   2017-09-16 [2] CRAN (R 4.0.2)
 digest        0.6.25  2020-02-23 [2] CRAN (R 4.0.2)
 dplyr         1.0.2   2020-08-18 [1] CRAN (R 4.0.2)
 ellipsis      0.3.1   2020-05-15 [2] CRAN (R 4.0.2)
 evaluate      0.14    2019-05-28 [2] CRAN (R 4.0.2)
 fansi         0.4.1   2020-01-08 [2] CRAN (R 4.0.2)
 generics      0.0.2   2018-11-29 [2] CRAN (R 4.0.2)
 glue          1.4.2   2020-08-27 [1] CRAN (R 4.0.2)
 htmltools     0.5.0   2020-06-16 [2] CRAN (R 4.0.2)
 httr          1.4.2   2020-07-20 [2] CRAN (R 4.0.2)
 jsonlite      1.7.1   2020-09-07 [1] CRAN (R 4.0.2)
 knitr         1.30    2020-09-22 [1] CRAN (R 4.0.2)
 lifecycle     0.2.0   2020-03-06 [2] CRAN (R 4.0.2)
 lubridate     1.7.9   2020-06-08 [2] CRAN (R 4.0.2)
 magrittr      1.5     2014-11-22 [2] CRAN (R 4.0.2)
 pillar        1.4.6   2020-07-10 [2] CRAN (R 4.0.2)
 pkgconfig     2.0.3   2019-09-22 [2] CRAN (R 4.0.2)
 plyr          1.8.6   2020-03-03 [2] CRAN (R 4.0.2)
 purrr         0.3.4   2020-04-17 [2] CRAN (R 4.0.2)
 R.cache       0.14.0  2019-12-06 [2] CRAN (R 4.0.2)
 R.methodsS3   1.8.1   2020-08-26 [1] CRAN (R 4.0.2)
 R.oo          1.24.0  2020-08-26 [1] CRAN (R 4.0.2)
 R.utils       2.10.1  2020-08-26 [1] CRAN (R 4.0.2)
 R6            2.4.1   2019-11-12 [2] CRAN (R 4.0.2)
 Rcpp          1.0.5   2020-07-06 [2] CRAN (R 4.0.2)
 RefManageR    1.2.12  2019-04-03 [1] CRAN (R 4.0.2)
 rlang         0.4.7   2020-07-09 [2] CRAN (R 4.0.2)
 rmarkdown     2.3     2020-06-18 [2] CRAN (R 4.0.2)
 rstudioapi    0.11    2020-02-07 [2] CRAN (R 4.0.2)
 rvest         0.3.6   2020-07-25 [2] CRAN (R 4.0.2)
 scholar       0.1.7   2018-07-03 [1] CRAN (R 4.0.2)
 sessioninfo   1.1.1   2018-11-05 [2] CRAN (R 4.0.2)
 stringi       1.5.3   2020-09-09 [1] CRAN (R 4.0.2)
 stringr       1.4.0   2019-02-10 [2] CRAN (R 4.0.2)
 tibble        3.0.3   2020-07-10 [2] CRAN (R 4.0.2)
 tidyselect    1.1.0   2020-05-11 [2] CRAN (R 4.0.2)
 vctrs         0.3.4   2020-08-29 [1] CRAN (R 4.0.2)
 vitae         0.2.2   2020-04-27 [1] CRAN (R 4.0.2)
 withr         2.3.0   2020-09-22 [1] CRAN (R 4.0.2)
 xfun          0.17    2020-09-09 [1] CRAN (R 4.0.2)
 xml2          1.3.2   2020-04-23 [2] CRAN (R 4.0.2)
 yaml          2.2.1   2020-02-01 [2] CRAN (R 4.0.2)

[1] U:/R/4.0.2
[2] C:/Program Files/R/R-4.0.2/site-library
[3] C:/Program Files/R/R-4.0.2/library`

**Comment by mitchelloharawild** [comment]
Some relevant discussion can be brought up with some searching:
- https://community.rstudio.com/t/failed-to-run-c-pdflatex-exe/49079/9
- https://github.com/yihui/tinytex/issues/208

I believe this isn't specific to the `{vitae}` package, but rather an issue with your installation / setup of tinytex/rmarkdown/R.
