### ISSUE TITLE
Bold/italic formatting in bulleted details

### ISSUE THREAD

**Issue by dvanic** [mitchelloharawild/vitae#134]
I am not sure how to add bold/italic formatting to bulleted details lists (or whether this is possible at all? or where to wrangle with the latex?).

Brief description of the problem:

```r
mytest <- tibble::tribble(
~Position, ~Year, ~Institution,       ~Where,     ~Classification,                              ~Details,
"Best Job Ever",  2020,   "CompanyX", "Antarctica", "Penguin wrangling", "Did x with y; z with f and N with K",
"Best Job Ever",  2020,   "CompanyX", "Antarctica",   "Polar bear hunt", "Did x with y; z with f and N with K"
)

# this doesn't give the desired output
mytest %>%
detailed_entries(
    what = Position, 
    when = Year, 
    with = Institution, 
    where = Where, 
    why = glue::glue(
      "\\textbf{<Classification>}: <Details>",  .open = "<", .close = ">"))

# neither does using **Classification** in the source csv file
```

Is there a way of doing this?

Desired output (of Achievements lines)

- **Penguin wrangling**: Did x with y; z with f and N with K
- **Polar bear hunt**: Did x with y; z with f and N with K

**Comment by mitchelloharawild** [comment]
You can use the `.protect = FALSE` option to allow text to be handled as raw inputs for LaTeX.

**Comment by dvanic** [comment]
Thanks, that works!
