### ISSUE TITLE
itemize in description even when string is empty

### ISSUE THREAD

**Issue by eborbath** [mitchelloharawild/vitae#135]
Hi,

Thanks for making your package available! 

I am using the `awesomecv` style. I am having an issue with entries that have an empty description field. In this case, the generated pdf file included an empty unordered list, with a standalone bullet. I would like to avoid that, and not start the `itemize` when the description field is empty. I have tried playing around with `ifempty` in the `cvitems` section of `awesome-cv.cls` file, but could not figure it out. I would appreciate if you could let me know where to edit the respective cls file, to solve the issue.

To replicate the issue, the chunk below provides one example:

```
```{r education}
tribble(
  ~ study, ~ university, ~ loc, ~ dates, ~ details,
  "Erasmus student at the Department of Political Science and Public Administration", "Middle East Technical University", "Ankara, TR", "Sep. 2011 - Jan. 2012", "") %>% 
  detailed_entries(study, dates, university, loc, details, .protect=FALSE)
```

Which results in:

![Capture](https://user-images.githubusercontent.com/9773005/95021437-409c7a80-0671-11eb-9834-6118eb2f3c8e.PNG)

I would like the bullet point where the description would be to disappear.

**Comment by mitchelloharawild** [comment]
When using `detailed_entries()`, if you don't want to use a specific field it can be omitted.

Try this:

````
```{r education}
tribble(
  ~ study, ~ university, ~ loc, ~ dates, ~ details,
  "Erasmus student at the Department of Political Science and Public Administration", "Middle East Technical University", "Ankara, TR", "Sep. 2011 - Jan. 2012", "") %>% 
  detailed_entries(study, dates, university, loc, .protect=FALSE)
```
````

**Comment by eborbath** [comment]
Thanks! I knew that I can exclude `details` from the list, but these entries are scattered across the CV in larger blocks about education, further training, etc, and there are entries there which shold have the details included. Therefore, I can't exclude the `description` for the entire block.

**Comment by mitchelloharawild** [comment]
I see, there needs to be a better / alternative interface for this which accepts a list structure instead.
You may be able to replace `""` with `"\empty"` when `.protect = FALSE`, but I haven't tested if this works.

**Comment by eborbath** [comment]
I have tried with `\\empty` since `\` is an escape character, but it does not work.

**Comment by mitchelloharawild** [comment]
I've added a change which considers `""` as `\empty`, could you see if this works for you?

**Comment by eborbath** [comment]
I get an error in R saying:

```
! Undefined control sequence.
<argument> \@@scl
```

This is how the `tex` log file ends:
```

Package: rerunfilecheck 2016/05/16 v1.8 Rerun checks for auxiliary files (HO)
Package uniquecounter Info: New unique counter `rerunfilecheck' on input line 2
82.
)
\Hy@SectionHShift=\skip81
))
! Undefined control sequence.
<argument> \@@scl 
                  
l.35 \definecolor{awesome}{HTML}{0}
```

**Comment by mitchelloharawild** [comment]
This seems unrelated to the change. Try deleting some side-effect files of the LaTeX build, perhaps you have some .aux files left over from a previous render?

**Comment by eborbath** [comment]
Not sure, I deleted the folder with all latex files. Re-installed vitae using `devtools` and `install_github("mitchelloharawild/vitae")` but I still get the same error:

```
output file: CV.knit.md
! Undefined control sequence.
<argument> \@@scl 
Error: LaTeX failed to compile CV.tex. See https://yihui.org/tinytex/r/#debugging for debugging tips. See CV.log for more info.
Execution halted
```

In the tex log file:

```
\pdfm@box=\box71
\c@Hy@AnnotLevel=\count313
\HyField@AnnotCount=\count314
\Fld@listcount=\count315
\c@bookmark@seq@number=\count316
("C:\Program Files\MiKTeX 2.9\tex/latex/oberdiek\rerunfilecheck.sty"
Package: rerunfilecheck 2016/05/16 v1.8 Rerun checks for auxiliary files (HO)
Package uniquecounter Info: New unique counter `rerunfilecheck' on input line 2
82.
)
\Hy@SectionHShift=\skip81
))
! Undefined control sequence.
<argument> \@@scl 
                  
l.35 \definecolor{awesome}{HTML}{0}
```
 
I think the error is in the headcolor variable defined in the first part. Previously this worked. I tried different versions, even deleted it, but I still get the error. You can also test it with the following .Rmd:

```
---
name: So So
headcolor: 000000
date: "`r format(Sys.time(), '%B %Y')`"
output: vitae::awesomecv
always_allow_html: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
library(vitae)
library(dplyr)
```

header
==================================

```{r education}
tribble(
  ~ study, ~ university, ~ loc, ~ dates, ~ details,
  "Erasmus student at the Department of Political Science and Public Administration", "Middle East Technical University", "Ankara, TR", "Sep. 2011 - Jan. 2012", "") %>% 
  detailed_entries(study, dates, university, loc, details, .protect=FALSE)
```

```

**Comment by mitchelloharawild** [comment]
The issue here is that `headcolor: 000000` is being converted to `headcolor: 0` (presumably by pandoc?). To correctly specify the headcolor it should be provided as a string: `headcolor: "000000"`.

Fixing this issue, there is another issue as the Awesome-CV template requires at least one social link (this can probably be fixed in the cls file if you don't want any social links).


````
---
name: So So
date: "`r format(Sys.time(), '%B %Y')`"
headcolor: "000000"
github: mitchelloharawild/vitae
output: vitae::awesomecv
always_allow_html: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
library(vitae)
library(dplyr)
```

header
==================================

```{r education}
tribble(
  ~ study, ~ university, ~ loc, ~ dates, ~ details,
  "Erasmus student at the Department of Political Science and Public Administration", "Middle East Technical University", "Ankara, TR", "Sep. 2011 - Jan. 2012", "") %>% 
  detailed_entries(study, dates, university, loc, details, .protect=FALSE)
```

````

**Comment by eborbath** [comment]
Thanks, it works well!

**Comment by andburch** [comment]
Unfortunately, I have the same problem and this does NOT work for me... Running the code you have above (now quote below) gives me that weird empty bullet. Did things somehow get reverted or something? I'm using the current github version of vitae...

> ---
> name: So So
> date: "`r format(Sys.time(), '%B %Y')`"
> headcolor: "000000"
> github: mitchelloharawild/vitae
> output: vitae::awesomecv
> always_allow_html: yes
> ---
> 
> ```{r setup, include=FALSE}
> knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
> library(vitae)
> library(dplyr)
> ```
> 
> header
> ==================================
> 
> ```{r education}
> tribble(
>   ~ study, ~ university, ~ loc, ~ dates, ~ details,
>   "Erasmus student at the Department of Political Science and Public Administration", "Middle East Technical University", "Ankara, TR", "Sep. 2011 - Jan. 2012", "") %>% 
>   detailed_entries(study, dates, university, loc, details, .protect=FALSE)
> ```

**Comment by mitchelloharawild** [comment]
Closing as this has been answered in #187.
