### ISSUE TITLE
Markdown formatting *within* `detailed_entries` or `brief_entries`

### ISSUE THREAD

**Issue by EliGurarie** [mitchelloharawild/vitae#138]
Thanks for a lovely tool for "semi-automating" classy-looking cv's!

One item - either unsupported or I'm missing something: when using the `detailed_entries` or `brief_entries` functions, it seems that all additional formatting is lost. This makes some sense - as the formatting is prescribed by the style - but perhaps there's a way to loosen this?  Italicizing, say, dissertation titles or species names would be very useful, or monotyping package names. 

For example:
```{r}
tibble(Degree = "Ph.D.", Subject = "Navel-gazing", Where = "Fancy Place", Year = "1990-2020", 
          Title = "Dissertation:  *What? Where? Why? When? Whither*")  %>% 
  detailed_entries(what = Degree, when = Year, where = Where, why = Title, with = Subject)
```

Produces something like this:

> 1990-2020 **Ph.D.**, Navel-gazing, Fancy Place.
> - Dissertation: `*`What? Where? Why? When? Whither`*`

And this:

```{r}
tibble(Degree = "Ph.D.", Subject = "Navel-gazing", Where = "Fancy Place", Year = "1990-2020", 
          Title = "Dissertation:  \emph{What? Where? Why? When? Whither}")  %>% 
  detailed_entries(what = Degree, when = Year, where = Where, why = Title, with = Subject)
```
produces this:

> 1990-2020 **Ph.D.**, Navel-gazing, Fancy Place.
> - Dissertation: \emph{What? Where? Why? When? Whither}

i.e. - no italics.   

Maybe there can be a function argument that lets LaTeX markup be processed by the compiler?  My work-around is to use the raw LaTeX `\detailedsection{\detaileditem{}{}{}, ...}`, which is  tedious, especially for longer sections. 

Alternatively - and even more flexibly / conveniently - would be some way to just have a two argument function that leaves the time-frame in the (typically) left column and the content written up in raw LaTeX, e.g.:

```{r}
timestamped_entries(when = "2020", what = "\\textbf{Ph.D.} in Navel-gazing from Fancy Place \\\  $\bullet$ Dissertation title: \emph{What? Where? Why? When? Whither}"
```
giving the desired output.  If the functionality already exists and I just haven't found it, do enlighten!

**Comment by BaxW** [comment]
I think you can get the behavior you want by adding  `.protect=FALSE`  to your `detailed_entries()` call. 
For instance, this code gives me an italicized title for the dissertation:
`tibble(Degree = "Ph.D.", Subject = "Navel-gazing", Where = "Fancy Place", Year = "1990-2020", 
          Title = "Dissertation:  \\emph{What? Where? Why? When? Whither}")  %>% 
  detailed_entries(what = Degree, when = Year, where = Where, why = Title, with = Subject, .protect = F)`

I have to do a double backslash to denote the LaTeX code or else I get an invalid escape error.

**Comment by EliGurarie** [comment]
`.protect = FALSE` pretty much nails it.  Thanks!

**Comment by mitchelloharawild** [comment]
That said, I would also like to add a `.markdown` option to format markdown inputs.
