### ISSUE TITLE
Removed from CRAN

### ISSUE THREAD

**Issue by SteffenMoritz** [mitchelloharawild/vitae#139]
Hi Mitchell, 
just wanted to give vitae a try and realized it got removed from CRAN, because the dependency 'RefManageR' got archived.
(I downloaded it from archive now)
```
Package ‘vitae’ was removed from the CRAN repository.
Formerly available versions can be obtained from the archive.
Archived on 2020-10-27 as reauired archived package 'RefManageR'.
```

Sounds like the RefManageR accidentally uploaded a new version to CRAN that did not comply to CRAN policies. But it seems like a solution and re-upload to CRAN is already in progress. ( see also https://github.com/ropensci/RefManageR/issues/79 )

So maybe you can re-upload the package once RefManageR is up again 👍

**Comment by mitchelloharawild** [comment]
Thanks for letting me know, I will submit an update to CRAN today which does not depend on the RefManageR package.
A bit disappointing that this is my first notification of the package being removed.

**Comment by mitchelloharawild** [comment]
`{vitae}` is back on CRAN now. Thanks again.
