### ISSUE TITLE
bibliography_entries() does not work on Windows

### ISSUE THREAD

**Issue by jooyoungseo** [mitchelloharawild/vitae#140]
@mitchelloharawild Would you mind testing whether `vitae::bibliography_entries()` works on windows?

I used Pandoc 2.10.1 on Windows 10 x64, and found that the minimal example was throwing errors.

## Test File Content

````
---
name: Marie
surname: Curie
position: "Professor"
address: "School of Physics & Chemistry, École Normale Supérieure"
phone: +1 22 3333 4444
www: mariecurie.com
email: "Marie.Curie@ens.fr"
twitter: mariecurie
github: mariecurie
linkedin: mariecurie
date: "`r format(Sys.time(), '%B %Y')`"
output: vitae::awesomecv
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
library(vitae)
```

# R Packages

```{r}
knitr::write_bib(c("vitae", "knitr", "rmarkdown"), "packages.bib")
bibliography_entries("packages.bib")
```
````

## Rendering Results

    rmarkdown::render("C:/test/test-cv/test.Rmd")
    #> processing file: test.Rmd
    #> Warning in utils::citation(..., lib.loc = lib.loc): no date field in DESCRIPTION
    #> file of package 'knitr'
    #> Warning in utils::citation(..., lib.loc = lib.loc): no date field in DESCRIPTION
    #> file of package 'rmarkdown'
    #> Warning in utils::citation(..., lib.loc = lib.loc): no date field in DESCRIPTION
    #> file of package 'vitae'
    #> output file: test.knit.md
    #> "C:/PROGRA~3/CHOCOL~1/bin/pandoc" +RTS -K512m -RTS test.utf8.md --to latex --from markdown+autolink_bare_uris+tex_math_single_backslash --output test.tex --lua-filter "C:\PROGRA~1\R\R-40~1.3\library\RMARKD~1\RMARKD~1\lua\PAGEBR~1.LUA" --lua-filter "C:\PROGRA~1\R\R-40~1.3\library\RMARKD~1\RMARKD~1\lua\LATEX-~1.LUA" --self-contained --template "C:\PROGRA~1\R\R-40~1.3\library\vitae\RMARKD~1\TEMPLA~1\AWESOM~1\RESOUR~1\AWESOM~1.TEX" --highlight-style tango --pdf-engine xelatex --lua-filter "C:\Users\sjysk\AppData\Local\Temp\RtmpgBZ8pR/multiple-bibliographies.lua"
    #> Error: pandoc document conversion failed with error 83

<sup>Created on 2020-11-04 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9001)</sup>

<details style="margin-bottom:10px;">
<summary>
Session info
</summary>

    sessioninfo::session_info()
    #> - Session info ---------------------------------------------------------------
    #>  setting  value                       
    #>  version  R version 4.0.3 (2020-10-10)
    #>  os       Windows 10 x64              
    #>  system   x86_64, mingw32             
    #>  ui       RTerm                       
    #>  language (EN)                        
    #>  collate  English_United States.1252  
    #>  ctype    English_United States.1252  
    #>  tz       America/New_York            
    #>  date     2020-11-04                  
    #> 
    #> - Packages -------------------------------------------------------------------
    #>  package     * version    date       lib
    #>  assertthat    0.2.1      2019-03-21 [1]
    #>  backports     1.1.10     2020-09-15 [1]
    #>  cli           2.1.0      2020-10-12 [1]
    #>  crayon        1.3.4      2017-09-16 [1]
    #>  digest        0.6.27     2020-10-24 [1]
    #>  dplyr         1.0.2      2020-08-18 [1]
    #>  ellipsis      0.3.1      2020-05-15 [1]
    #>  evaluate      0.14       2019-05-28 [1]
    #>  fansi         0.4.1      2020-01-08 [1]
    #>  fs            1.5.0      2020-07-31 [1]
    #>  generics      0.1.0      2020-10-31 [1]
    #>  glue          1.4.2      2020-08-27 [1]
    #>  highr         0.8        2019-03-20 [1]
    #>  htmltools     0.5.0.9002 2020-11-01 [1]
    #>  knitr         1.30.2     2020-10-25 [1]
    #>  lifecycle     0.2.0      2020-03-06 [1]
    #>  magrittr      1.5        2014-11-22 [1]
    #>  pillar        1.4.6      2020-07-10 [1]
    #>  pkgconfig     2.0.3      2019-09-22 [1]
    #>  purrr         0.3.4      2020-04-17 [1]
    #>  R.cache       0.14.0     2019-12-06 [1]
    #>  R.methodsS3   1.8.1      2020-08-26 [1]
    #>  R.oo          1.24.0     2020-08-26 [1]
    #>  R.utils       2.10.1     2020-08-26 [1]
    #>  R6            2.5.0      2020-10-28 [1]
    #>  reprex        0.3.0.9001 2020-10-25 [1]
    #>  rlang         0.4.8      2020-10-08 [1]
    #>  rmarkdown     2.5.3      2020-11-04 [1]
    #>  sessioninfo   1.1.1      2018-11-05 [1]
    #>  stringi       1.5.3      2020-09-09 [1]
    #>  stringr       1.4.0      2019-02-10 [1]
    #>  styler        1.3.2      2020-02-23 [1]
    #>  tibble        3.0.4      2020-10-12 [1]
    #>  tidyselect    1.1.0      2020-05-11 [1]
    #>  vctrs         0.3.4      2020-08-29 [1]
    #>  vitae       * 0.2.2.9000 2020-11-04 [1]
    #>  withr         2.3.0      2020-09-22 [1]
    #>  xfun          0.19.2     2020-11-03 [1]
    #>  yaml          2.2.1      2020-02-01 [1]
    #>  source                                  
    #>  CRAN (R 4.0.3)                          
    #>  CRAN (R 4.0.3)                          
    #>  CRAN (R 4.0.3)                          
    #>  CRAN (R 4.0.3)                          
    #>  CRAN (R 4.0.3)                          
    #>  CRAN (R 4.0.3)                          
    #>  CRAN (R 4.0.3)                          
    #>  CRAN (R 4.0.3)                          
    #>  CRAN (R 4.0.3)                          
    #>  CRAN (R 4.0.3)                          
    #>  CRAN (R 4.0.3)                          
    #>  CRAN (R 4.0.3)                          
    #>  CRAN (R 4.0.3)                          
    #>  Github (rstudio/htmltools@0741213)      
    #>  local                                   
    #>  CRAN (R 4.0.3)                          
    #>  CRAN (R 4.0.3)                          
    #>  CRAN (R 4.0.3)                          
    #>  CRAN (R 4.0.3)                          
    #>  CRAN (R 4.0.3)                          
    #>  CRAN (R 4.0.3)                          
    #>  CRAN (R 4.0.3)                          
    #>  CRAN (R 4.0.3)                          
    #>  CRAN (R 4.0.3)                          
    #>  CRAN (R 4.0.3)                          
    #>  Github (tidyverse/reprex@d3fc4b8)       
    #>  CRAN (R 4.0.3)                          
    #>  Github (rstudio/rmarkdown@bb7d952)      
    #>  CRAN (R 4.0.3)                          
    #>  CRAN (R 4.0.3)                          
    #>  CRAN (R 4.0.3)                          
    #>  CRAN (R 4.0.3)                          
    #>  CRAN (R 4.0.3)                          
    #>  CRAN (R 4.0.3)                          
    #>  CRAN (R 4.0.3)                          
    #>  Github (mitchelloharawild/vitae@cc72b14)
    #>  CRAN (R 4.0.3)                          
    #>  Github (yihui/xfun@97ca2fb)             
    #>  CRAN (R 4.0.3)                          
    #> 
    #> [1] C:/Program Files/R/R-4.0.3/library

</details>

**Comment by mitchelloharawild** [comment]
Could you provide a minimal sample of the bib file causing this error?
This may be related: https://stackoverflow.com/questions/36826916/pandoc-citeproc-error-83-with-rmarkdown-file

**Comment by mitchelloharawild** [comment]
After fixing some unrelated issues with the file path, it seems to work for me:
``` r
rmarkdown::render("~/vitae/Untitled/Untitled.Rmd")
#> processing file: Untitled.Rmd
#> Warning in citation(pkg, auto = if (pkg == "base") NULL else TRUE): no date
#> field in DESCRIPTION file of package 'vitae'
#> Warning in citation(pkg, auto = if (pkg == "base") NULL else TRUE): could not
#> determine year for 'vitae' from package DESCRIPTION file
#> output file: Untitled.knit.md
#> "C:/Program Files/RStudio/bin/pandoc/pandoc" +RTS -K512m -RTS Untitled.utf8.md --to latex --from markdown+autolink_bare_uris+tex_math_single_backslash --output Untitled.tex --lua-filter "C:\Users\Admin\Documents\R\win-library\4.0\rmarkdown\rmarkdown\lua\pagebreak.lua" --lua-filter "C:\Users\Admin\Documents\R\win-library\4.0\rmarkdown\rmarkdown\lua\latex-div.lua" --self-contained --template "C:\Users\Admin\Documents\R\win-library\4.0\vitae\rmarkdown\templates\awesomecv\resources\awesome-cv.tex" --highlight-style tango --pdf-engine xelatex --lua-filter "C:\Users\Admin\AppData\Local\Temp\Rtmp4G7cb3/multiple-bibliographies.lua"
#> 
#> Output created: Untitled.pdf
```

<sup>Created on 2020-11-04 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

<details>

<summary>Session info</summary>

``` r
sessionInfo()
#> R version 4.0.2 (2020-06-22)
#> Platform: x86_64-w64-mingw32/x64 (64-bit)
#> Running under: Windows 10 x64 (build 18363)
#> 
#> Matrix products: default
#> 
#> locale:
#> [1] LC_COLLATE=English_United States.1252 
#> [2] LC_CTYPE=English_United States.1252   
#> [3] LC_MONETARY=English_United States.1252
#> [4] LC_NUMERIC=C                          
#> [5] LC_TIME=English_United States.1252    
#> 
#> attached base packages:
#> [1] stats     graphics  grDevices utils     datasets  methods   base     
#> 
#> other attached packages:
#> [1] vitae_0.2.2.9000
#> 
#> loaded via a namespace (and not attached):
#>  [1] crayon_1.3.4.9000 digest_0.6.27     dplyr_1.0.2       R6_2.4.1         
#>  [5] lifecycle_0.2.0   magrittr_1.5      evaluate_0.14     pillar_1.4.6     
#>  [9] highr_0.8         rlang_0.4.8       stringi_1.4.6     ellipsis_0.3.1   
#> [13] generics_0.1.0    vctrs_0.3.4       rmarkdown_2.5     tools_4.0.2      
#> [17] stringr_1.4.0     glue_1.4.2        tinytex_0.27      purrr_0.3.4      
#> [21] xfun_0.19         yaml_2.2.1        compiler_4.0.2    pkgconfig_2.0.3  
#> [25] htmltools_0.5.0   tidyselect_1.1.0  knitr_1.29        tibble_3.0.3
```

</details>

**Comment by jooyoungseo** [comment]
Yes, I have confirmed now it works. Thanks @mitchelloharawild!
