### ISSUE TITLE
bold (or other style) inside the entries

### ISSUE THREAD

**Issue by Courvoisier13** [mitchelloharawild/vitae#143]
I would like to add a boold style inside one of the entries below. For example I would like the "details" word below to be in bold. is that doable in this package? `\textbf{details}` would not work because it get sanitized, and `\\textbf{details}` becomes `\textbf\{details\}` in the LaTeX.

```r
tribble(
  ~Year, ~Type, ~company, ~Where, ~details,
  "March 2020-", "X", "ABC", "London, UK", "writing software",
  "March 2020-", "X", "ABC", "London, UK", "details: Very good software"
) %>% 
  detailed_entries(what = Type, when = Year, with = company, where = Where, why = details
  )
```

**Comment by mitchelloharawild** [comment]
You can prevent sanitising inputs by setting `.protect = FALSE` in `detailed_entries()`.
