### ISSUE TITLE
`detailed_entries()` always adds a newline, even when `why` is empty

### ISSUE THREAD

**Issue by jansim** [mitchelloharawild/vitae#144]
Hello,

I've noticed a problem when using the new version of `vitae`: It seems that when knitting the `awesomecv` template `detailed_entries()` will always add an empty newline, even when `why` is not specified or a row is `NA`.

---

I was able to reproduce the problem by creating the awesomecv template via the Rstudio GUI (New File => Rmarkodown => From Template => Curriculum Vitae (Awesome Cv Format) for v0.3.0 (where the issue occurs) and v0.2.2 (where it does not occur). Versions were switched using `renv`. I've also attached the two rendered PDFs.

v0.3.0 (issue)             |  v0.2.2 (correct)
:-------------------------:|:-------------------------:
<img width="726" alt="v0 3 0" src="https://user-images.githubusercontent.com/7115629/99905834-502c5d00-2ccb-11eb-9692-c65ecde47d32.png">  |  <img width="726" alt="v0 2 2" src="https://user-images.githubusercontent.com/7115629/99905832-4d316c80-2ccb-11eb-9e46-18d37cd88fd6.png">
[v0.3.0.pdf](https://github.com/mitchelloharawild/vitae/files/5579609/v0.3.0.pdf) | [v0.2.2.pdf](https://github.com/mitchelloharawild/vitae/files/5579610/v0.2.2.pdf)

Session Info:
```
R version 4.0.3 (2020-10-10)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS Catalina 10.15.7

Matrix products: default
BLAS:   /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/4.0/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
 [1] crayon_1.3.4     digest_0.6.27    dplyr_1.0.2      R6_2.5.0        
 [5] lifecycle_0.2.0  magrittr_2.0.1   evaluate_0.14    pillar_1.4.6    
 [9] rlang_0.4.8      rstudioapi_0.13  ellipsis_0.3.1   vctrs_0.3.4     
[13] generics_0.1.0   rmarkdown_2.5    tools_4.0.3      glue_1.4.2      
[17] purrr_0.3.4      xfun_0.19        yaml_2.2.1       compiler_4.0.3  
[21] pkgconfig_2.0.3  htmltools_0.5.0  vitae_0.3.0      tidyselect_1.1.0
[25] knitr_1.30       tibble_3.0.4

> rmarkdown::pandoc_version()
[1] ‘2.11.2’
```

**Comment by mitchelloharawild** [comment]
Should be fixed now, thanks for your bug report.

**Comment by jansim** [comment]
Awesome, thanks! ☺️
