### ISSUE TITLE
 object 'vec_proxy_order' is not exported by 'namespace:vctrs'

### ISSUE THREAD

**Issue by ifeomaozo** [mitchelloharawild/vitae#146]
Please briefly describe your problem and what output you expect. If you have a question, please don't use this form. Instead, ask on <https://stackoverflow.com/> or <https://community.rstudio.com/>.

Please include a minimal reproducible example (AKA a reprex). If you've never heard of a [reprex](https://reprex.tidyverse.org/) before, start by reading <https://www.tidyverse.org/help/#reprex>.

---

Brief description of the problem

```r
#108 When knitting the package in R, I had the aforementioned error: object 'vec_proxy_order' is not exported by 'namespace:vctrs'
I tried to download the development version from git to see if that helps but still same problem 
```

**Comment by mitchelloharawild** [comment]
Please provide a minimally reproducible example that gives you this error.

**Comment by mitchelloharawild** [comment]
You'll need to update your {vctrs} package. The vitae package requires at least version 0.3.3.
This is now specified in the DESCRIPTION.
