### ISSUE TITLE
Cannot knit CV due to missing pandoc-citeproc

### ISSUE THREAD

**Issue by adamhsparks** [mitchelloharawild/vitae#148]
The markdown knits but the conversion fails.

```r
output file: Adam_H_Sparks_CV.knit.md

pandoc: pandoc-citeproc: createProcess: runInteractiveProcess: exec: does not exist (No such file or directory)
Error: pandoc document conversion failed with error 1
Execution halted
```

Not sure if this is the right spot to report it? But this is the first I've run into the issue, when I attempted to update my CV.

On macOS if you attempt to install pandoc-citeproc, you get this:

```bash
❯ brew install pandoc-citeproc                                                                   
Error: pandoc-citeproc has been disabled because it is deprecated upstream!
```

**Comment by mitchelloharawild** [comment]
Are you using the latest CRAN release of vitae? There was some code included specifically to improve this issue.
Which version of pandoc are you using?
``` r
rmarkdown::pandoc_version()
#> [1] '2.11.2'
```

<sup>Created on 2020-12-17 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by adamhsparks** [comment]
I was using the latest CRAN version, had the error, and then tried installing from this repository.

Pandoc is latest version as well.

```r
rmarkdown::pandoc_version()
#> [1] '2.11.2'
```

**Comment by mitchelloharawild** [comment]
I've pushed some changes to the lua filter to the `lua-bib` branch, could you try it out? The changes assume that the pandoc version is >= 2.11, and so pandoc-citeproc does not appear anywhere in the lua filter. Hopefully it works or we get a different error?

I'm wondering if the issues are mac specific, because I have been able to convert documents on linux and windows without issue.

**Comment by adamhsparks** [comment]
Hmm. I think it's me, not you.

Using a template from _vitae_ works fine but my own CV won't knit.

**Comment by mitchelloharawild** [comment]
Do you have a repo for your CV that I can try to build?

**Comment by adamhsparks** [comment]
Sorry, yes I do, but I forgot I'd made changes to how my CV knit. I'm using _bookdown_ to knit my CV so I don't know if that helps. It really _is_ me, I was in the wrong spot. It does use _vitae_ but this wasn't the cause of the problem that I was seeing.

It was a custom lua file for multiple bibliographies that needed to be updated. This file to be specific, https://github.com/adamhsparks/AHSparks_CV/blob/main/lua/multiple-bibliographies.lua.

However, if you want to see my CV after all of this, here it is. https://github.com/adamhsparks/AHSparks_CV

Sorry for bothering you with this, @mitchelloharawild. Thanks for the great work on _vitae_!

**Comment by mitchelloharawild** [comment]
Great, glad you've figured it out.

Indeed with pandoc v2.11, pandoc-citeproc has been merged with pandoc.

The changes made in the latest CRAN release of vitae incorporate the multiple bibliographies lua filter directly into the `bibliography_entries()` function, and so the bibliography is now generated with pandoc and supports CSL style files. Essentially your YAML bibliography files can be replaced with `bibliography_entries()` if you prefer.

**Comment by adamhsparks** [comment]
That's awesome, thanks for the tip, @mitchelloharawild. I'll have a go with that. 🙏

**Comment by mitchelloharawild** [comment]
Thinking about this more, it'll need to be used with the `cv_document()` (of which all CV styles use internally for `vitae`) output format for this to work. I wonder if it can be made to work with other output formats... :thinking: 

The reason for this is that `cv_document()` adds the necessary lua filter used by `bibliography_entries()` to the pandoc convert call.
