### ISSUE TITLE
Create hyperlink using DOI in publications section

### ISSUE THREAD

**Issue by norcalbiostat** [mitchelloharawild/vitae#149]
Suggested enhancement: If a DOI is provided in a .bib file, use it to create a hyperlink in the publications section. Or just include it in the citation as a clickable hyperlink.

**Comment by mitchelloharawild** [comment]
You should be able to do this using a custom / different CSL file.

For example, the `apa.csl` bibliography style automatically links DOIs. This style (and many others) can be obtained from: https://github.com/citation-style-language/styles/blob/master/apa.csl

An example of how a custom CSL can be specified is below:

---

`your_cv.rmd`

````
---
name: vitae
position: "package"
date: "`r format(Sys.time(), '%B %Y')`"
csl: apa.csl
output: 
  vitae::hyndman:
    keep_tex: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
library(vitae)
```

# Publications

```{r}
bibliography_entries("your_bibliography.bib")
```
````
