### ISSUE TITLE
knit error ( error in gsub)

### ISSUE THREAD

**Issue by hosi133** [mitchelloharawild/vitae#150]
I tried to follow installation instruction and knit twenty seconds cv but got an error output.

Error in gsub("<<PANDOC_PATH>>", rmarkdown::find_pandoc()$dir, fixed = TRUE,  : 
  이 로케일에서는 입력문자열 2는 유효하지 않습니다
Calls: <Anonymous> ... do.call -> <Anonymous> -> cv_document -> cat -> gsub
실행이 정지되었습니다 

Could I get an advice for solving this error?

**Comment by mitchelloharawild** [comment]
Could you provide a minimal reproducible example?

**Comment by mitchelloharawild** [comment]
Closing as MRE not provided. If you are able to provide an MRE, you can reopen this issue.
