### ISSUE TITLE
Compiling Error due to the `pandoc-citeproc`

### ISSUE THREAD

**Issue by sammo3182** [mitchelloharawild/vitae#151]
Thank you so very much for the package! It's amazing! It worked pretty well until...I guess, `pandoc` updating to 2.11. From then on I would not be able to compile the cv because of the following error: 

```
pandoc.exe: pandoc-citeproc: createProcess: does not exist (No such file or directory)
Error: pandoc document conversion failed with error 1
Execution halted
```

I searched around and found it might relate to the update of `pandoc`. It changes the `pandoc-citepro` to `citepro` (See the discussion here: https://github.com/rstudio/bookdown/issues/1022#issuecomment-737841262). The newest `rmarkdown` seems fitting the new pandoc already, but `vitae` appears not. 

I'll appreciate if you could have a check on this issue.  I attached a toy example for your to replicate. Please ensure to use the latest version of Rstudio or Pandoc after version 2.11. 

Thank you!

[04_cv.zip](https://github.com/mitchelloharawild/vitae/files/5824078/04_cv.zip)

**Comment by sammo3182** [comment]
Uhm... I noticed that you did update the `multiple-bibliographies.lua` which is identical to the latest version from the `pandoc` except for adding the `<<PATH>>`. But, I still got the error as mentioned above, unless I rolled back to Pandoc 2.10.1. Any idea why? Sorry if that's actually a pandoc rather than `vitae` issue...

**Comment by mitchelloharawild** [comment]
If you're using a custom lua filter (as shown in your zip), you will need to update it for the changes to `pandoc-citeproc` and `pandoc` (as you mention above).

This package already handles multiple bibliographies using a very similar lua filter. You don't need to include the lua filter in the YAML header, as it is automatically included if/when `bibliography_entries()` is used.

This RMD shows how `bibliography_entries()` can be used with the contents of your zip above:
````
---
given: vitae
surname: package
output: vitae::hyndman
---


```{r, include=FALSE}
library(vitae)
```


```{r}
bibliography_entries("a.bib")
bibliography_entries("b.bib")
```

````
![image](https://user-images.githubusercontent.com/16127127/105867346-1a984d00-6049-11eb-8af8-f421c03fe794.png)

**Comment by sammo3182** [comment]
The problem does not completely solved, but you are right, `bibliography_entries` works well without the lua filter. The issue is that `rmarkdown::pandoc_citeproc_convert` used by `bibliography_entries` does not produce correct CJK characters (at least in Windows). 

At the same time, I tried to use the new version of [ `multiple-bibliographies.lua`](https://github.com/mitchelloharawild/vitae/blob/master/inst/multiple-bibliographies.lua) attached in `vitae`, and it does not work with the following error message:

```
PandocFilterError "<<PANDOC_PATH>>/pandoc" "Could not find executable <<PANDOC_PATH>>/pandoc"
```

I spent a morning trying to modifying the lua file, but, as a knowing-zero for pandoc, I failed. A more practical way for me is still rolling back to Pandoc 2.10. 
This is thus not a request for reopening the issue. It's more a report for some other CJK bib users.
But if you have a little bit of time, it would be wonderful if you could help writing out an executable `multiple-bibliographies.lua`.
Thank you, again, for the fantastic package!

**Comment by mitchelloharawild** [comment]
You'll need to replace `<<PANDOC_PATH>>` with the path to your `pandoc` installation.

**Comment by sammo3182** [comment]
Ah! That's the trick! The document compiled, with two issues, though: 

1. Using  either Pandoc 2.10 or 2.11, the bibliography cannot correctly present until I replaced the codes in the function `create_topic_bibliography ` from 

```
local is_bib = div.identifier == 'bibliography'
  if not is_bib then
    return nil
  end
  local bibfile = div.content[1].content[1].text
```

to 

```
local name = div.identifier:match('^refs([_%w]*)$')
  local bibfile = name and doc_meta['bibliography' .. name]
  if not bibfile then
    return nil
  end
```

2. When using Pandoc 2.11, the pdf output works pretty well. But when trying the new `markdowncv` template, the bib content overlaps with the subsection titles like this:

![image](https://user-images.githubusercontent.com/6463211/106574333-c07e1700-6575-11eb-88ce-980d4ce61c9b.png)

Since the pdf is the major type I rely on, I'm already pretty satisfied with the outcome. Thank you again for the help!

**Comment by mitchelloharawild** [comment]
Glad it is working well for you now.

The `div.identifier` change is because `{vitae}` uses a different interface for specifying multiple bibliographies based on the `div.content` instead of the `doc_meta`. The `markdowncv` template should use some custom css for correctly positioning the `bibliography_entries()` content, as shown in the preview:
![](https://raw.githubusercontent.com/mitchelloharawild/vitae/master/man/figures/preview-markdowncv.png)

Do you have a minimal example that shows this overlapping issue?
