### ISSUE TITLE
Customising style of CSL bibliography

### ISSUE THREAD

**Issue by mitchelloharawild** [mitchelloharawild/vitae#153]
> Hi there
> 
> Rather than opening a new issue I thought I'd ask here:
> 
> I use bibliography_entries a few times throughout my .Rmd and I would like to change the font size and the indentations for the numbered list in the final PDF. I couldn't quite figure out from the above how that would be done - the raw LaTeX answer (e.g. \setlenght{\parindent} doesn't help since it's a function call to bibliography_entries, and I didn't find a place in the awesomecv CSL where I could change _just_ the numbered list/bibliography .
> 
> e.g. How do I change the font size / indent / etc that results from this:
> 
> ```
> bibliography_entries("Presentations.bib")
> ```
> 
> I'm using
> 
> Am I missing something obvious?
> 
> Thanks so much
> 
> Hugo

_Originally posted by @HugoBothaMD in https://github.com/mitchelloharawild/vitae/issues/122#issuecomment-771268662_

**Comment by mitchelloharawild** [comment]
An example output for a CSL generated bibliography entry is:

```
\leavevmode\hypertarget{ref-Rvitae}{}%
\CSLLeftMargin{51. }
\CSLRightInline{O'Hara-Wild, M, Hyndman, RJ, Xie, Y, Krewinkel, A, \&
Seo, J. (2021). \emph{vitae: Curriculum Vitae for R Markdown} (Version
0.4.0). \url{https://CRAN.R-project.org/package=vitae}}
```

The style of these entries can be customised using by modifying these Pandoc CSL macro commands in the template .tex file:
```
% Pandoc CSL macros
\newlength{\cslhangindent}
\setlength{\cslhangindent}{1.5em}
\newlength{\csllabelwidth}
\setlength{\csllabelwidth}{3em}
\newenvironment{CSLReferences}[3] % #1 hanging-ident, #2 entry spacing
 {% don't indent paragraphs
  \setlength{\parindent}{0pt}
  % turn on hanging indent if param 1 is 1
  \ifodd #1 \everypar{\setlength{\hangindent}{\cslhangindent}}\ignorespaces\fi
  % set entry spacing
  \ifnum #2 > 0
  \setlength{\parskip}{#2\baselineskip}
  \fi
 }%
 {}
\usepackage{calc}
\newcommand{\CSLBlock}[1]{#1\hfill\break}
\newcommand{\CSLLeftMargin}[1]{\parbox[t]{\csllabelwidth}{\hfill #1~}}
\newcommand{\CSLRightInline}[1]{\parbox[t]{\linewidth - \cslhangindent - \csllabelwidth}{#1}\vspace{0.8ex}}
\newcommand{\CSLIndent}[1]{\hspace{\cslhangindent}#1}

```

**Comment by HugoBothaMD** [comment]
Perfect, thanks! I found a nice example of this implementation from JooYoung Seo, which I missed even though it's linked from the main page

https://github.com/jooyoungseo/jy_CV
