### ISSUE TITLE
Package not listed in CRAN

### ISSUE THREAD

**Issue by storopoli** [mitchelloharawild/vitae#156]
Is there something wrong with the CV's CRAN status?

Tried in several mirrors, Linux and macOS.

``` r
install.packages("CV")
#> Warning: package 'CV' is not available for this version of R
#> 
#> A version of this package for your version of R might be available elsewhere,
#> see the ideas at
#> https://cran.r-project.org/doc/manuals/r-patched/R-admin.html#Installing-packages
```

<sup>Created on 2021-02-14 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

My `sessionInfo()`

``` r
sessionInfo()
#> R version 4.0.3 (2020-10-10)
#> Platform: x86_64-apple-darwin17.0 (64-bit)
#> Running under: macOS Big Sur 10.16
#> 
#> Matrix products: default
#> BLAS:   /Library/Frameworks/R.framework/Versions/4.0/Resources/lib/libRblas.dylib
#> LAPACK: /Library/Frameworks/R.framework/Versions/4.0/Resources/lib/libRlapack.dylib
#> 
#> locale:
#> [1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8
#> 
#> attached base packages:
#> [1] stats     graphics  grDevices utils     datasets  methods   base     
#> 
#> loaded via a namespace (and not attached):
#>  [1] crayon_1.4.1      digest_0.6.27     backports_1.2.1   lifecycle_0.2.0  
#>  [5] reprex_1.0.0      magrittr_2.0.1    evaluate_0.14     pillar_1.4.7     
#>  [9] highr_0.8         stringi_1.5.3     rlang_0.4.10      fs_1.5.0         
#> [13] vctrs_0.3.6       ellipsis_0.3.1    rmarkdown_2.6     styler_1.3.2     
#> [17] tools_4.0.3       stringr_1.4.0     glue_1.4.2        purrr_0.3.4      
#> [21] xfun_0.21         yaml_2.2.1        compiler_4.0.3    pkgconfig_2.0.3  
#> [25] htmltools_0.5.1.1 knitr_1.31        tibble_3.0.6
```

<sup>Created on 2021-02-14 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

**Comment by mitchelloharawild** [comment]
Thanks for letting me know, I have sent a patch release to CRAN yesterday which will hopefully bring it back on CRAN.

**Comment by storopoli** [comment]
Sure no problem. Big fan of your work. Glad to help. If you have any news from CRAN, let me know so that I can test it with GitHub Actions and also in my own computers.

**Comment by mitchelloharawild** [comment]
Thanks! The check issues can be found here: https://cran-archive.r-project.org/web/checks/2021/2021-02-11_check_results_vitae.html

I have submitted a patch fix which only runs these examples if a sufficient pandoc version is available, hopefully this is enough to get `{vitae}` back on CRAN.

**Comment by mitchelloharawild** [comment]
It should be back on CRAN very soon, I've just received approval from the maintainers.
