### ISSUE TITLE
Publications not "listing"

### ISSUE THREAD

**Issue by WilhelminavanDijk** [mitchelloharawild/vitae#166]
Please briefly describe your problem and what output you expect. If you have a question, please don't use this form. Instead, ask on <https://stackoverflow.com/> or <https://community.rstudio.com/>.

Please include a minimal reproducible example (AKA a reprex). If you've never heard of a [reprex](https://reprex.tidyverse.org/) before, start by reading <https://www.tidyverse.org/help/#reprex>.

---

Hi, when knitting a resume with the "modern" template, the bibliography is not outputting as an indented list, but instead as unindented paragraphs. (The template example does show it is supposed to be indented). Is there a way to adjust any of the files to either make the lists indented, or if not, add spacing between items?

![Screen Shot 2021-03-31 at 3 20 28 PM](https://user-images.githubusercontent.com/64925394/113199140-c5d5a600-9234-11eb-9d9d-51344f740465.png)

I did not change anything to the yaml   (am using ..  output: vitae::moderncv)
```r
bibliography_entries("PeerreviewedPapers.bib") %>%
 arrange(desc(issued))


```
[PeerreviewedPapers.bib.txt](https://github.com/mitchelloharawild/vitae/files/6238985/PeerreviewedPapers.bib.txt)

**Comment by mitchelloharawild** [comment]
I am unable to reproduce this issue. Please provide a complete MRE, as there may be some other changes causing the issue.

You can also try removing the moderncv.cls file, which will replace it with the default one from the package next time you knit.

![image](https://user-images.githubusercontent.com/16127127/133175552-04c45260-4027-4d24-b9c9-22ffbd93cba9.png)
