### ISSUE TITLE
Taking quite long for a knitting 

### ISSUE THREAD

**Issue by SeokLeeUS** [mitchelloharawild/vitae#168]
as the title described, I am not sure what I did wrong, but it took long to complete a knitting..

**Comment by mitchelloharawild** [comment]
Could you provide more information? Possibly an example? Is it faster when you knit a second time?

**Comment by SeokLeeUS** [comment]
when the profile photo is changed to mine (small size <40kb) from mariecurie.jpg, it stuck and doesn't make a progress at all.

**Comment by SeokLeeUS** [comment]
what version of R should I use for this?

**Comment by mitchelloharawild** [comment]
Does it knit quickly with the default profile photo?
Any version of R that you are able to install the package with should work.

**Comment by mitchelloharawild** [comment]
Closing as stale.
