### ISSUE TITLE
?cv_formats not existing

### ISSUE THREAD

**Issue by kw-fn** [mitchelloharawild/vitae#171]
In documentation it's stated that: "A list of output formats provided by the package can be found with ?cv_formats."

---

> ?cv_formats
No documentation for ‘cv_formats’ in specified packages and libraries:
you could try ‘??cv_formats’

```r
library('vitae')
?cv_formats
```
Using R 4.0.4.

**Comment by mitchelloharawild** [comment]
Thanks, this was missed when changing the structure of templates. You can now find a list of templates on the website (or README): https://pkg.mitchelloharawild.com/vitae/#templates
