### ISSUE TITLE
Feature request: Show total page number

### ISSUE THREAD

**Issue by jmbarbone** [mitchelloharawild/vitae#172]
It would be nice to add in as an optional feature for the output to provide the total number of pages at the bottom rather than just the current page number.  I've implemented a quick fix myself but didn't include anything to toggle this.  The necessary changes can be seen in a [forked repo](https://github.com/jmbarbone/vitae/commit/e625967d008df2e1490f097c5d0f83cd3c658360) and the result can be seen [in another repo](https://github.com/jmbarbone/barbone-cv/blob/b66ed4f303885cfd6ddb747b49fc5e30d66b5128/Barbone-CV.pdf).

**Comment by mitchelloharawild** [comment]
Thanks for the suggestion. You can now specify
```yaml
output: 
  vitae::awesomecv:
    page_total: true
```

To get page totals in the `awesomecv()` template.
