### ISSUE TITLE
bibliography_entries: Error: Can't subset columns that don't exist.

### ISSUE THREAD

**Issue by tormodb** [mitchelloharawild/vitae#174]
---

After recently updated my r-packages, previous running code is no longer working. When I try to read a .bib file containing references, the following error occurs:  

```r
# bibliography_entries("file.bib")
# Error: Can't subset columns that don't exist.
# x Column `other-ids` doesn't exist.
```

> rlang::last_error()
<error/vctrs_error_subscript_oob>
Can't subset columns that don't exist.
x Column `other-ids` doesn't exist.
Backtrace:
  1. vitae::bibliography_entries("file.bib")
  3. tibble:::`[.tbl_df`(csl_fields, unique(vec_c(!!!lapply(bib, names))))
  4. tibble:::vectbl_as_col_location(...)
  7. vctrs::vec_as_location(j, n, names)
  9. vctrs:::stop_subscript_oob(...)
 10. vctrs:::stop_subscript(...)
Run `rlang::last_trace()` to see the full context.

**Comment by mitchelloharawild** [comment]
Could you provide a sample of `file.bib` which produces this error?

**Comment by tormodb** [comment]
Hi, I sure can and have attached it to this message.

For now, I was able to replace the function with ReadBib from RefManageR which seems to work fine after conversion to tibble.

Hilsen Tormod

**Comment by mitchelloharawild** [comment]
I think you'll have to attach it using the GitHub website, email attachments don't come through.

**Comment by tormodb** [comment]
Sorry. I was not able to upload *.bib files to GitHub (not supported) so I had to rename the extension before uploading. If you revert it back to file.bib it should work. 

[tpubs_zot.txt](https://github.com/mitchelloharawild/vitae/files/6699908/tpubs_zot.txt)

**Comment by mitchelloharawild** [comment]
Thanks for your reprex, the 'other-ids' field (produced from some of your entries having the 'ids' entry) was not part of the expected schema in vitae. I've added a fallback to character vectors for these fields.
