### ISSUE TITLE
moderncv won't compile tex file

### ISSUE THREAD

**Issue by meflynn** [mitchelloharawild/vitae#176]
There may be an obvious solution to this, but when I try to compile a moderncv file with any of its themes I consistently get the following error:

! LaTeX Error: Command \researcheridsocialsymbol undefined.

I thought it might be triggered by the social arguments in the YAML but this happens even with the most bare bones YAML/file setup. and no other content. I've looked through the style files, too, but I'm not sure if this is an issue with an sty file or the tex template.  Thanks for your help!
---
title: CV
output: 
  vitae::moderncv:
    theme: "banking"
---

**Comment by meflynn** [comment]
I dug into the tex template too but couldn't find any calls to this particular command.

**Comment by meflynn** [comment]
I resolved the issue. The moderncv.cls file was missing several social media/networking symbol commands under the "% other symbols" section. I've pasted the list below that resolved the issue. Note that the first one appears to be a spelling variation on one that was already listed. 

\newcommand*{\researcheridsocialsymbol}{}
\newcommand*{\googlescholarsocialsymbol}{}
\newcommand*{\telegramsocialsymbol}{}
\newcommand*{\whatsappsocialsymbol}{}
\newcommand*{\signalsocialsymbol}{}
\newcommand*{\matrixsocialsymbol}{}
\newcommand*{\bornsymbol}{}

**Comment by marthinsen** [comment]
I have the same problem. I looks to me like a general issue. ​Should this issue be reopened? 

The moderncv template test fails on both Windows and Linux for me. But your suggested changes fixes it. Do you mind if I make a PR out of it?

**Comment by meflynn** [comment]
I think I accidentally closed this prematurely. Probably a good idea to reopen for the developer to address.

**Comment by mitchelloharawild** [comment]
Thanks for the fix @meflynn, and for @marthinsen for the PR.

**Comment by meflynn** [comment]
Happy to help! Love the package.
