### ISSUE TITLE
Would like to pass a list

### ISSUE THREAD

**Issue by rjake** [mitchelloharawild/vitae#185]
Very cool resume package! I'm noticing that a list object would be easier for me to maintain than a `tribble()` or `csv` files. I'm curious if you could have a function that takes a list like this and feeds the named elements to the right arguments of `detailed_entries()`. I was hoping to use a `do.call()` or `pmap()` but the first argument needs to be `data`. I sketched out the solution below. I'm not sure it works 💯 when knit but it has looked ok in my attempts. I'm not great at `rlang` but maybe it gives you some ideas.

```r
library(glue)
library(rlang)

list_to_entry <- function(x) {
  df <- purrr::map_dfr(x, as_tibble)
  f <- detailed_entries
  
  # rearrange formals
  formal_names <- names(formals(f))
  
  explicit_args <- 
    match(
      c("data", names(df)),
      formal_names
    )
    
  missing_args <- setdiff(seq_along(formal_names), explicit_args)
  
  formals(f) <- formals(f)[c(explicit_args, missing_args)]

  # make expr
  expr(f(df, !!!parse_exprs(names(df)))) |> 
    eval()
}

list(
  list(
    with = "Flying University",
    when = "1889-91",
    what = "Informal studies",
    where = "Warsaw, Poland"
  ),
    list(
    with = "Sorbonne Université",
    when = "1893",
    what = "Master of Physics",
    where = "Paris, France"
  )
) |> 
  list_to_entry()

# with                when    what              where          why      
# <chr>               <chr>   <chr>             <chr>          <list>   
# Flying University   1889-91 Informal studies  Warsaw, Poland <chr [0]>
# Sorbonne Université 1893    Master of Physics Paris, France  <chr [0]>
```

**Comment by rjake** [comment]
Sure, that does the trick. Part of it was that the input object already has the names of the arguments so you wouldn't need to specify them. So if I gave you a df with `with` and `where`, those would plug into the right arguments and the rest would be NA. It's not that much effort to type them in as you have in your example but might be convenient. Feel free to close.

**Comment by mitchelloharawild** [comment]
Thanks for the suggestion - I could add default columns to look for in the `*_entries()` functions, but I think it is clearer to specifically map the columns from the dataset to the output entries.
