### ISSUE TITLE
awesomecv.tex does not take Pandoc options

### ISSUE THREAD

**Issue by fansi-sifan** [mitchelloharawild/vitae#186]
The  `\documentclass` argument in `awesome.tex` file is not passing on the YAML header to the template. 

I'm using vitae::awesomecv(), and I was not able to change the default page size from a4 to letter. Adding Pandoc options `classoption: letterpaper` to the Rmarkdown file works fine on `twentysecondcv`, but not on `awesomecv`.

Looks like this is what's missing from `awesomecv.tex`:

`\documentclass[$if(fontsize)$$fontsize$$else$10pt$endif$,$if(lang)$$babel-lang$,$endif$$if(papersize)$$papersize$$else$a4paper$endif$,$for(classoption)$$classoption$$sep$,$endfor$]{twentysecondcv}`

**Comment by mitchelloharawild** [comment]
Fixed, thanks!
