### ISSUE TITLE
Using bibliography entries for Publications but from Google Scholar data

### ISSUE THREAD

**Issue by meteakca** [mitchelloharawild/vitae#188]
Hi,
I was wondering if it is possible to use the `bibliography_entries` format for the publications that we import using `scholar` package.

With the scholar package, I can import my publications with citation counts into a data frame. And, I can print them using the `detailed_entries` option. But the default formats are not APA formatted, unlike the default `bibliography_entries` format. So, I was wondering if I can somehow apply the styling from `bibliography_entries` to my dataframe from scholar.

Thanks for the great package!

---

**Comment by mitchelloharawild** [comment]
To use `bibliography_entries()` you'll need to use a pandoc-citeproc compatible bibliography file (such as `*.bib`, CSL-JSON, or YAML). The outputs from the `{scholar}` package aren't enough to reconstruct these formats as it scrapes from the search results webpage. Instead, you'll need need to access the contents of the cite feature for each resulting article. Best software for this I know of is the `{scholarly}` Python library - https://scholarly.readthedocs.io/en/latest/quickstart.html#bibtex

Generally the bib files in Google Scholar results aren't always reliable, so if you have a different bibtex file source that would be preferred.

**Comment by meteakca** [comment]
Got it, thanks!
