### ISSUE TITLE
The change in the name of the citation breaks the bibliograpy_entries function

### ISSUE THREAD

**Issue by vvader24** [mitchelloharawild/vitae#213]
I am building a reading list with the `vitae` package as it involves multiple bibliography entries. It can render the documnet perfectly well if I have the following entry in my .bib file,

--------
@article{ray2021various,
  title={Various dimension reduction techniques for high dimensional data analysis: a review},
  author={Ray, Papia and Reddy, S Surender and Banerjee, Tuhina},
  journal={Artificial Intelligence Review},
  volume={54},
  number={5},
  pages={3473--3515},
  year={2021},
  publisher={Springer}
}
--------
However, it breaks if I change the name of the article like in the example below

--------
@Ray2021{ray2021various,
  title={Various dimension reduction techniques for high dimensional data analysis: a review},
  author={Ray, Papia and Reddy, S Surender and Banerjee, Tuhina},
  journal={Artificial Intelligence Review},
  volume={54},
  number={5},
  pages={3473--3515},
  year={2021},
  publisher={Springer}
}
--------

Is there a way I could change the names and build references with the bibliographies?
![Screen Shot 2022-06-12 at 3 13 11 PM](https://user-images.githubusercontent.com/61251388/173255744-ec32ae2b-f386-428a-86e5-636e297ba76b.png)

**Comment by mitchelloharawild** [comment]
Articles are renamed using the first input within `{}`, not the `@tag`. For example, you would rename the latter via:

```
@Article{ray2021,
title={Various dimension reduction techniques for high dimensional data analysis: a review},
author={Ray, Papia and Reddy, S Surender and Banerjee, Tuhina},
journal={Artificial Intelligence Review},
volume={54},
number={5},
pages={3473--3515},
year={2021},
publisher={Springer}
}
```
