### ISSUE TITLE
footer not showing - awesomecv template

### ISSUE THREAD

**Issue by mainahandmaker** [mitchelloharawild/vitae#224]
I couldn't get a footer to appear on my cv using the awesomecv template, though everything else is knitting and working perfectly. I updated all relevant packages, and am running the latest version of RStudio and R version 4.2.2. This is also occurring without changing a single thing about the awesomecv template. When I open a new .Rmd > From Template and choose Curriculum Vitae (AwesomeCV-format), when I knit everything renders except the footer. Specifying `show_footer: true` in the YAML does not change this. From what I've seen online the template defaults to showing the footer with name, "curriculum vitae," and page number. Any thoughts on what else could be causing this default setting not to show up? Attaching the .cls, .Rmd., and .pdf files generated when knitting without making any changes to the awesomecv template. 
[no_footer.zip](https://github.com/mitchelloharawild/vitae/files/9915861/no_footer.zip)

**Comment by mitchelloharawild** [comment]
Could you try using the latest development version of this package? This sounds similar to an issue I've fixed recently: https://github.com/mitchelloharawild/vitae/commit/935d63d9863761bf5218530cf20e4aeece682599

**Comment by mainahandmaker** [comment]
Brilliant! That fixed it. Thank you so much!!

**Comment by mitchelloharawild** [comment]
You're welcome :)
