### ISSUE TITLE
Footer in Awasome template

### ISSUE THREAD

**Issue by jmmartinf** [mitchelloharawild/vitae#226]
My footer in the PDF output using "awesomecv" template do not show the footer with Date, Name and File name.

In old versions I didn't have that issue.

However I just saw the library changelog with a change in the version (vitae 0.5.2), described as: Added option to remove footer from awesomecv template ([#182](https://github.com/mitchelloharawild/vitae/issues/182), [#200](https://github.com/mitchelloharawild/vitae/issues/200)).

Reading the documentation, the function "awesomecv()" has a parameter named "show_footer" with default value to TRUE.

Reviewing the latex template (awasome-cv.tex), in line 166 the code is:
"$if(showfooter)$"

Therefore there is a small but significant difference, the hyphen.

I had to change tha code to
"$if(show_footer)$"

And the the problem was solved.

Saludos y Gracias

---

```r
# output: vitae::awesomecv
```

**Comment by flyaflya** [comment]
fix noted above works great.  you can find the template location from R using:

```
system.file("rmarkdown", "templates", "awesomecv",
            "resources", "awesome-cv.tex",
            package = "vitae"
)
```

modify the file and the footer appears!

**Comment by mitchelloharawild** [comment]
Great, glad this could be figured out!
