### ISSUE TITLE
Undefined control sequence.

### ISSUE THREAD

**Issue by gtalckmin** [mitchelloharawild/vitae#235]
Hello,

I just downloaded the vitae package and try to knit using the MarieCurie.rmd skeleton example. The following error
```
output file: MarieCurie.knit.md

! Undefined control sequence.
<argument> \cvpronouns 



! Undefined control sequence.
l.60 \cvpronouns
                {} % Pronouns 


```

Anything I should do or add either on the *.tex template or on the *.cls file to correct this?
Thanks

**Comment by cjdbarlow** [comment]
For those who stumbled across this I have had the same issue with version 5.3. Rolling back to the previous release helped me:

packageurl <- "https://cran.r-project.org/src/contrib/Archive/vitae/vitae_0.5.2.tar.gz"
install.packages(packageurl, repos=NULL, type="source")
