### ISSUE TITLE
Widen awards section's third column

### ISSUE THREAD

**Issue by sbreitbart** [mitchelloharawild/vitae#238]
Is there a way to widen the Awards sections' third column (denoting the awarding organization)? Right now, most of the entries in that column have to take up two lines. Thanks!

```
tribble(
  ~ award, ~ from, ~ year,
  "Scholarship", "organization", "year") %>%
  brief_entries(award, year, from) 
```

**Comment by mitchelloharawild** [comment]
Changes to the style would need to occur to the template's cls file.
For example, in awesomecv you can change the cvhonors style here: https://github.com/mitchelloharawild/vitae/blob/7fb420df020c95356f4311e02fe59dab495140c8/inst/rmarkdown/templates/awesomecv/skeleton/awesome-cv.cls#L657-L686
