### ISSUE TITLE
PDF<-->MS Word Production

### ISSUE THREAD

**Issue by vfulco** [mitchelloharawild/vitae#24]
Can't find an 'enhancement' label but one of biggest issues as an R user and professional resume writer is that too many employers and agencies ask for MS Word versions.  While I abhor that format, it is reality.  The great LaTex typsetting gets destroyed running through Pandoc for .doc/.docx.  Although Rmarkdown is supposed to be able to render into Word nicely with a reference doc, that isn't the case. I must have 10 Word templates I can't wrestle into use because of this.

If anyone has trailheads on nearly identical formats creation, would appreciate!  Thanks all.

**Comment by bwiernik** [comment]
A non programmatic approach is to open the PDF using Word. Word does a pretty great job converting PDFs in many cases.

**Comment by weisisheng** [comment]
Thanks very much.  I am a libreoffice user having sworn off MSFT products whenever possible.  I will look into it though.

**Comment by weisisheng** [comment]
Reviewing the docs, I didn't see a yaml option to retain the intermediate.tex file, similar to plain vanilla Rmd-->pdf rendering, which can then be converted easily using pandoc.

Am I missing something (before I modify code myself)?

**Comment by mitchelloharawild** [comment]
It's the same as a plain rmd, `keep_tex: true`

**Comment by weisisheng** [comment]
Hmm...when I run this, I don't the intermediate one is not created.  Do I need to hard-code it in the package?

output: 
  vitae::twentyseconds:
    keep_tex: true

**Comment by mitchelloharawild** [comment]
For this, I don't think it is appropriate to provide tools for converting pdf output to word. Instead, word specific templates can be supported (requiring #93 to be implemented first).
If you have some word templates that you'd like supported, you can propose them in #4

**Comment by mitchelloharawild** [comment]
Closing as conversion from PDF to MS Word will not be supported. Instead, word specific templates can be provided as extensions (however this is not a priority, HTML templates will come next).
