### ISSUE TITLE
Decreasing header spacing

### ISSUE THREAD

**Issue by sbreitbart** [mitchelloharawild/vitae#240]
Hi there,

This is a great resume template! I began using it a few months ago and was able to decrease the header spacing from 1" to 0.5" by changing this line in my \Documents\R\win-library\4.1\pagedown\resources\css\resume.css file:

```
@page{
  size: letter portrait;
  margin: 0.4in 0.5in 0.4in 0.25in;
}
```

I updated Rstudio and now those settings aren't applying to my knitted pdf anymore. Do you have any advice?

**Comment by sbreitbart** [comment]
Found the answer in the second and third comments on [this post](https://stackoverflow.com/questions/73328631/pagedown-html-resume-how-to-increase-font-size-and-reduce-margins) , for anyone else with the same question.

**Comment by mitchelloharawild** [comment]
Wonderful, thanks for coming back and posting the answer.
Sorry I didn't get to this before you figured it out!
