### ISSUE TITLE
Error on LINUX system

### ISSUE THREAD

**Issue by Dix1976** [mitchelloharawild/vitae#248]
I cannot render any of the CVs, i have installes all missing LaTeX libs , after all are installed   it always end up  with  ! LaTeX Error: Something's wrong--perhaps a missing \item.  Any suggestion to solve ? 

---

Brief description of the problem

```r
# insert reprex here
```

**Comment by flyaflya** [comment]
this happens on Windows as well.  A similar issue is referenced here: https://github.com/mitchelloharawild/vitae/issues/246   

I cannot get the awesomeCV or any other CV template from within RStudio to work on Windows or Posit Cloud.  Even with the dev release, the issue persists.

**Comment by PaulParedes** [comment]
Same problem here. ! LaTeX Error: Something's wrong--perhaps a missing \item. I can not render to PDF. 

[paulparedes-cv-enero-2024.log](https://github.com/mitchelloharawild/vitae/files/13848174/paulparedes-cv-enero-2024.log)

xfun::session_info()
R version 4.2.2 Patched (2022-11-10 r83330)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Debian GNU/Linux 12 (bookworm), RStudio 2023.12.0.369

Locale:
  LC_CTYPE=es_PE.UTF-8       LC_NUMERIC=C               LC_TIME=es_PE.UTF-8        LC_COLLATE=es_PE.UTF-8     LC_MONETARY=es_PE.UTF-8   
  LC_MESSAGES=es_PE.UTF-8    LC_PAPER=es_PE.UTF-8       LC_NAME=C                  LC_ADDRESS=C               LC_TELEPHONE=C            
  LC_MEASUREMENT=es_PE.UTF-8 LC_IDENTIFICATION=C       

Package version:
  base64enc_0.1.3   bit_4.0.5         bit64_4.0.5       bslib_0.6.1       cachem_1.0.8      cli_3.6.2         clipr_0.8.0      
  compiler_4.2.2    cpp11_0.4.7       crayon_1.5.2      digest_0.6.33     dplyr_1.1.4       ellipsis_0.3.2    evaluate_0.23    
  fansi_1.0.6       fastmap_1.1.1     fontawesome_0.5.2 fs_1.6.3          generics_0.1.3    glue_1.6.2        graphics_4.2.2   
  grDevices_4.2.2   highr_0.10        hms_1.1.3         htmltools_0.5.7   jquerylib_0.1.4   jsonlite_1.8.8    knitr_1.45.10    
  lifecycle_1.0.4   magrittr_2.0.3    memoise_2.0.1     methods_4.2.2     mime_0.12         pillar_1.9.0      pkgconfig_2.0.3  
  prettyunits_1.2.0 progress_1.2.3    R6_2.5.1          rappdirs_0.3.3    readr_2.1.4       rlang_1.1.2       rmarkdown_2.25   
  rstudioapi_0.15.0 sass_0.4.8        stats_4.2.2       stringi_1.8.3     stringr_1.5.1     tibble_3.2.1      tidyselect_1.2.0 
  tinytex_0.49      tools_4.2.2       tzdb_0.4.0        utf8_1.2.4        utils_4.2.2       vctrs_0.6.5       vitae_0.5.4      
  vroom_1.6.5       withr_2.5.2       xfun_0.41         yaml_2.3.8

**Comment by PaulParedes** [comment]
Hi! My solution is installing vitae version 0.5.3 instaed of version 0.5.4. That works for me.
For the installation of 0.5.3:
- Delete vitae 0.5.4 
- packageurl <- "https://cran.r-project.org/src/contrib/Archive/vitae/vitae_0.5.3.tar.gz"
- install.packages(packageurl, repos = NULL, type = "source")

That's it.

**Comment by JJGabe** [comment]
While this is a very simple solution, I will be forever grateful to you @PaulParedes for pointing it out.

**Comment by atsyplenkov** [comment]
> Hi! My solution is installing vitae version 0.5.3 instaed of version 0.5.4. That works for me. For the installation of 0.5.3:
> 
> * Delete vitae 0.5.4
> * packageurl <- "https://cran.r-project.org/src/contrib/Archive/vitae/vitae_0.5.3.tar.gz"
> * install.packages(packageurl, repos = NULL, type = "source")
> 
> That's it.

That solution is also work on Windows machines. The 0.54 version seems not work at all

**Comment by adamhsparks** [comment]
Alas, reverting to 0.5.3 does not seem to work on my MacBook. This is a brand new machine I just received and set up on Monday this week.

**Comment by mitchelloharawild** [comment]
Closing in favor of the related discussion in #246 - downgrading to v0.5.3 should work if you have previously been able to use vitae, or potentially updating to a newer version of pandoc might also work.
