### ISSUE TITLE
Add previews of vitae templates and themes

### ISSUE THREAD

**Issue by mitchelloharawild** [mitchelloharawild/vitae#72]
This is common request, and would be a useful feature.
I haven't addressed this earlier as I'm unsure what the best approach would be, whilst keeping the package size minimal.

A few ideas I have had:

1. Include a copy of the PDF using the example code for each template/theme on the pkgdown website.
2. Include small lowres thumbnails of the rendered PDF for each of the output types. This may involve breaking up the output formats help file into separate pages, which is probably a good thing to do regardless.
3. ~~This thumbnail approach may also be helpful for the RStudio rmarkdown template selector, perhaps a 'thumbnail' or 'image' value in the `template.yaml` could be used to display a preview of each template. (This idea is outside the scope of vitae, although I'd be happy to contribute toward this feature).~~ (requires rstudio extension)

**Comment by isteves** [comment]
I had in mind screenshots in the README like done here: https://github.com/juba/rmdformats
Including a full PDF example would be a nice bonus (all their screenshots are linked to a full rendered html).  

2- also sounds neat though not sure how feasible it is with the roxygen to pkgdown flow (w/o some manual work on the pkgdown)
3- not 100% clear on what this means but I like the sound of it (does this mean that a little thumbnail will pop up when you type the template name in the yaml?)
