### ISSUE TITLE
NO block quotes when using the vitae package

### ISSUE THREAD

**Issue by leynu** [mitchelloharawild/vitae#75]
I am trying to create a simple **block quote** in my CV but the text comes **simple/plain text**. 
Is there a way to make it look like a quote?
Here is the Rmarkdown code I am trying to run:

````
---
name: My Name
date: "`r format(Sys.time(), '%B, %Y')`"
qualifications: MSc
position: Statistician
email: xxx@gmail.com
headcolor: 414141 ##FFBD33
output: vitae::awesomecv
#docname: curriculum vitae
---

```{r setup, include=FALSE}
library(vitae)
```

> "Life's a journey, not a destination.
> And I just can't tell just what tomorrow brings."
>
> `r tufte::quote_footer('--- Amazing by Aerosmith')`

````

**Comment by mitchelloharawild** [comment]
Most templates for vitaes don't have a defined quote style. Whatever the output is showing (in this case awesomecv), is the quote style provided by that template. If you'd like to improve the template style for quotes, feel free to submit a pull request.
