### ISSUE TITLE
Select bibliography entries

### ISSUE THREAD

**Issue by arnold-c** [mitchelloharawild/vitae#79]
I was wondering if there is a way to remove a particular field from the bib outputs? I have used `type` field in Zotero to flag certain items, e.g. "MChem" under the "Thesis" bibtype, but would like to remove "MChem" from the pdf printout. I thought `select( )` would work, much like `filter( )` does, but unfortunately it remains in the pdf. Below is the code I have used.

```
bibliography_entries(here("data", "arnold-c.bib")) %>%
  filter(bibtype == "Thesis" & type == "MChem") %>%
  select(-type)
```

I have checked that it does work when you create a tibble, just not when it comes to creating the pdf, i.e. the code below does remove `type` from the tibble `mchem`.

```
mchem <- bibliography_entries(here("data", "arnold-c.bib")) %>%
  filter(bibtype == "Thesis" & type == "MChem") %>%
  select(-type)
```

Any thoughts on what I could use instead?
Thanks,

**Comment by mitchelloharawild** [comment]
This is now possible as of v0.3.0.
