### ISSUE TITLE
Add support for html templates

### ISSUE THREAD

**Issue by mitchelloharawild** [mitchelloharawild/vitae#8]

**Comment by sk-sahu** [comment]
Is HTML output supported apart from PDF??

**Comment by mitchelloharawild** [comment]
Not yet. Supporting this would require HTML specific CV templates.
If you have suggestions for templates, feel free to leave them here.

**Comment by mitchelloharawild** [comment]
Closing as HTML template support is added in v0.3.0.
Actually adding a html template is appropriately tracked in issue #4.
