### ISSUE TITLE
Awesome CV Font Size

### ISSUE THREAD

**Issue by arnold-c** [mitchelloharawild/vitae#81]
Is there a way to adjust the font size of markdown text and bibligraphy references when using the awesome cv template? I've tried adjusting the fontsize values within the cls file, and none of them seem to be able to adjust these specific areas.

**Comment by wittja01** [comment]
I would also like to know if this is possible. It looks to me like these two sections of my CV have different font sizes, and I would like them to be the same. I've tried editing options in the .cls file to no success.

![image](https://user-images.githubusercontent.com/13739421/66159830-6ae6d280-e5ee-11e9-8df7-3be82214d272.png)

**Comment by mitchelloharawild** [comment]
This seems a little tricky - https://github.com/posquit0/Awesome-CV/issues/57
At least it isn't as simple as changing the document arguments like it is in other packages.

If someone would like to implement the method discussed in the linked issue, and map it to the fontsize pandoc variable, I would be happy to accept a PR.

**Comment by mitchelloharawild** [comment]
I have been playing around with my CV recently, and it appears that fontsize macros such as `\Huge`, `\small`, `\footnotesize` and `\tiny` work fine for the markdown text.

Changing the font size for the bibliography will be a bit more difficult, and perhaps depends on #88 being added.

**Comment by DanyangDai** [comment]
You can change the front size in the awesome-cv.cls file from line 194 to 237. Just change the \fontsize{14pt} into what you want it to be.

**Comment by arnold-c** [comment]
To follow up on this much later (as I've just been updating my CV), for some reason `bibliography_entries()` outputs to type `\honordatestyle`, so if you edit that section of the awesome-cv.cls file (in the section listed in this comment), it will update the bib font style.

> You can change the front size in the awesome-cv.cls file from line 194 to 237. Just change the \fontsize{14pt} into what you want it to be.
> 
> https://github.com/mitchelloharawild/vitae/blob/5b33de8744911467a51a6c40d4c649a69b126b49/inst/rmarkdown/templates/awesomecv/skeleton/awesome-cv.cls#L189-L237

**Comment by rempsyc** [comment]
I made a function for this: `scale_awesomecv_fonts(scale = 1.5)`. It extracts the relevant parts from `awesome-cv.cls` and scale them by a factor of x.

```r
scale_awesomecv_fonts <- function(scale = 1, file_path = "awesome-cv.cls", backup = TRUE) {
  if (!file.exists(file_path)) stop("File not found: ", file_path)
  if (backup) file.copy(file_path, paste0(file_path, ".bak"), overwrite = TRUE)
  lines <- readLines(file_path)
  pattern <- "\\\\fontsize\\{([0-9.]+)pt\\}\\{1em\\}"
  lines_scaled <- gsubfn::gsubfn(
    pattern,
    function(size = pattern) {
      size <- as.numeric(size)
      scaled <- round(size * scale, 2)
      paste0("\\fontsize{", scaled, "pt}{1em}")
    },
    lines
  )
  writeLines(lines_scaled, file_path)
  message("Font sizes scaled, baselineskip unchanged (1em).")
}
```

I could submit a PR if there is any interest.

**Comment by mitchelloharawild** [comment]
Very cool, thanks for sharing! I'd be happy to accept a PR for this.
