### ISSUE TITLE
Improve documentation (especially for `why` input)

### ISSUE THREAD

**Issue by achamess** [mitchelloharawild/vitae#84]
For detailed entries, it'd be nice to be able to add bulleted details, as is common for many CV entries, for example: https://drive.google.com/file/d/0B9DjC_ju-eVCQnl3NjJsUkN0LTA/view

Do you think this is possible? How would one code that into the tibble/dataframe? I imagine there would be some tinkering with the Latex template too.

**Comment by mitchelloharawild** [comment]
If you have duplicated entries for all other columns except the `why` input, it will be treated as a list.

The documentation will need to be improved to explain this.
