### ISSUE TITLE
bibliography custom edits

### ISSUE THREAD

**Issue by igordot** [mitchelloharawild/vitae#86]
I am just getting started with `vitae`, so this might be a really basic question. My biggest concern is with the bibliography section where automation really helps. What would be the optimal way to add non-standard formatting, such as highlighting a specific name or adding asterisks?

**Comment by mitchelloharawild** [comment]
Non-standard bibliography formatting will be supported when custom CSL files are supported (#52).
To create the custom format, you would create/edit your CSL file.
