### ISSUE TITLE
Add multiple bulleted entries in awesome_cv

### ISSUE THREAD

**Issue by cparsania** [mitchelloharawild/vitae#90]
How to add multiple bulleted  entries  in awesome_cv as shown in the figure below ?

/Users/chirag/Downloads/tt.png

**Comment by mitchelloharawild** [comment]
Multiple entries via bullets are added using the `why` input.

If the input data contains multiple duplicate rows for other inputs, with the `why` input column varying, these inputs will be collapsed into bullet points of a single entry.

```r
library(vitae)
library(tibble)
tribble(
  ~ What, ~ Why,
  "A", "Bullet 1",
  "A", "Bullet 2",
  "B", "Bullet 1"
) %>% 
  detailed_entries(what = What, why = Why)
```
