### ISSUE TITLE
Highlight author name in bib_entries

### ISSUE THREAD

**Issue by jooyoungseo** [mitchelloharawild/vitae#95]
It would be so nice if we could have a way to highlight author's name in bib_entries in CV.

I believe that it can be achieved through lua filter.

I have created [this issue](https://github.com/pandoc/lua-filters/issues/75#issue-520645397) regarding this functionality.

**Comment by mitchelloharawild** [comment]
I think this is out of the scope of vitae's `bibliography_entires()`.

You can generate markdown code that displays the entires in a similar way to a bibliography which also highlights your name.
