### ISSUE TITLE
Add support for date field in appropriate templates

### ISSUE THREAD

**Issue by jooyoungseo** [mitchelloharawild/vitae#96]
It would be nicer if we had `date` field in YAML for CV templates.

If date is provided, that could be used as a timestamp to indicate when the CV has been updated.

**Comment by mitchelloharawild** [comment]
Some templates (such as `hyndman`) automatically update the date input.
It would be nice if this could be controlled within YAML like most rmarkdown templates.

**Comment by mitchelloharawild** [comment]
Closing as the availability of the `date` field is dependent on the template.
`{vitae}` aims to provide rmarkdown interfaces to popular CV templates. Modifications to existing templates that do not impact the original appearance/behaviour of the template is allowable, but not a development priority. If someone were to add support for dates in templates (ideally in the original template's repo) I would happily add handlers for that template's `date` from the YAML inputs.
