### ISSUE TITLE
signature field is needed

### ISSUE THREAD

**Issue by jooyoungseo** [mitchelloharawild/vitae#97]
Some people put their signature in their CVs. Thus, it would be nicer if we had an optional `signature` field in YAML so that users can pass their signature image filename.

**Comment by mitchelloharawild** [comment]
A signature can be added as an image using standard markdown code.
Currently YAML fields are used for inputs which are positioned in unique locations by each template.

There are no templates supported which make use of signatures, so currently there is no need to add this into the YAML header.

```
![signature](path/to/my/signature.png)
```
